CREATE TABLE [Extract].[Aisles]
(
	[Aisle_Id] INT NOT NULL,
	[Aisle] NVARCHAR(100) NULL,
	[Meta_Id] BIGINT IDENTITY (1,1) NOT NULL,
	[Meta_CreateTime] DATETIME2 DEFAULT GETDATE() NOT NULL,

	CONSTRAINT PK_Aisles_Id PRIMARY KEY CLUSTERED ([Aisle_Id])
)
