--The create schema part is manually added.
--The tables: PLAN_TABLE, TOAD_PLAN_TABLE were manually excluded
--The SQL was generated on the PP environment 14/6-2018
CREATE SCHEMA DMSA;
GO
CREATE TABLE DMSA.AARSAGER_DIM(
   AARSAGER_DIM int NOT NULL PRIMARY KEY
  ,AARSAGER nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.AFLYSNING_DIM(
   AFLYSNING_DIM int NOT NULL PRIMARY KEY
  ,AFLYSNING_KODENR nvarchar(10)
  ,AFLYSNING_KODEVAERDI nvarchar(50)
  ,AFLYSNING_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.AKTTYPE_DIM(
   AKTTYPE_DIM int NOT NULL PRIMARY KEY
  ,AKTTYPE_X_KODENR_1 nvarchar(10)
  ,AKTTYPE_X_KODEVAERDI_1 nvarchar(10)
  ,AKTTYPE_X_TEKST_1 nvarchar(50)
  ,AKTTYPE_X_CONCAT_1 nvarchar(50)
  ,AKTTYPE_KODENR_2 nvarchar(10)
  ,AKTTYPE_KODEVAERDI_2 nvarchar(50)
  ,AKTTYPE_TEKST_2 nvarchar(100)
  ,AKTTYPE_CONCAT_2 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.ALDER_DIM(
   ALDER_DIM int NOT NULL PRIMARY KEY
  ,ALDER_KODE_1 nvarchar(10)
  ,ALDER_NAVN_1 nvarchar(10)
  ,ALDER_SORT_1 nvarchar(10)
  ,ALDER_CONCAT_1 nvarchar(10)
  ,ALDER_KODE nvarchar(10)
  ,ALDER_NAVN nvarchar(10)
  ,ALDER_SORT nvarchar(10)
  ,ALDER_CONCAT nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.ANMELDERTYPE_DIM(
   ANMELDERTYPE_DIM int NOT NULL PRIMARY KEY
  ,ANMELDERTYPE_KODE_1 nvarchar(1)
  ,ANMELDERTYPE_NAVN_1 nvarchar(100)
  ,ANMELDERTYPE_SORT_1 nvarchar(1)
  ,ANMELDERTYPE_CONCAT_1 nvarchar(100)
  ,ANMELDERTYPE_KODE_2 nvarchar(20)
  ,ANMELDERTYPE_NAVN_2 nvarchar(20)
  ,ANMELDERTYPE_SORT_2 nvarchar(20)
  ,ANMELDERTYPE_CONCAT_2 nvarchar(50)
  ,ANMELDERTYPE_KODE nvarchar(10)
  ,ANMELDERTYPE_NAVN nvarchar(100)
  ,ANMELDERTYPE_SORT nvarchar(10)
  ,ANMELDERTYPE_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.ANTAL_AARSVAERK_DIM(
   ANTAL_AARSVAERK_DIM int NOT NULL PRIMARY KEY
  ,ANTAL_AARSVAERK_KODE nvarchar(10)
  ,ANTAL_AARSVAERK_NAVN nvarchar(50)
  ,ANTAL_AARSVAERK_SORT nvarchar(1)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.ANTAL_ANSATTE_2_DIM(
   ANTAL_ANSATTE_2_DIM int NOT NULL PRIMARY KEY
  ,ANTAL_ANSATTE_2_KODE nvarchar(10)
  ,ANTAL_ANSATTE_2_NAVN nvarchar(50)
  ,ANTAL_ANSATTE_2_SORT nvarchar(1)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.ANTAL_ANSATTE_DIM(
   ANTAL_ANSATTE_DIM int NOT NULL PRIMARY KEY
  ,ANTAL_ANSATTE_KODE nvarchar(10)
  ,ANTAL_ANSATTE_NAVN nvarchar(50)
  ,ANTAL_ANSATTE_SORT nvarchar(1)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.ARBEJDSMILJOEPROBLEM_DIM(
   ARBEJDSMILJOEPROBLEM_DIM int NOT NULL PRIMARY KEY
  ,AMP_TYPE_KODENR_1 nvarchar(10)
  ,AMP_TYPE_KODEVAERDI_1 nvarchar(20)
  ,AMP_TYPE_TEKST_1 nvarchar(100)
  ,AMP_EMNE_KODENR_2 nvarchar(10)
  ,AMP_EMNE_KODEVAERDI_2 nvarchar(10)
  ,AMP_EMNE_TEKST_2 nvarchar(100)
  ,AMP_EMNE_CONCAT_2 nvarchar(100)
  ,AMP_EMNE_KODENR_3 nvarchar(10)
  ,AMP_EMNE_KODEVAERDI_3 nvarchar(10)
  ,AMP_EMNE_TEKST_3 nvarchar(100)
  ,AMP_EMNE_CONCAT_3 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.ATVIRK_DIM(
   ATVIRK_DIM int NOT NULL PRIMARY KEY
  ,ANR int
  ,ATVIRK_NAVN nvarchar(250)
  ,ENHEDSTYPE nvarchar(50)
  ,ADRESSE nvarchar(250)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,KOORDINERENDECENTER_NR int
  ,KOORDINERENDECENTER_NAVN nvarchar(50)
  ,STATUS int
  ,STATUS_TEKST nvarchar(20)
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO date
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BELIGGENHEDSCENTER_DIM(
   BELIGGENHEDSCENTER_DIM int NOT NULL PRIMARY KEY
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BESOEGSROLLE_DIM(
   BESOEGSROLLE_DIM int NOT NULL PRIMARY KEY
  ,BESOEGSROLLE_KODENR nvarchar(10)
  ,BESOEGSROLLE_KODEVAERDI nvarchar(20)
  ,BESOEGSROLLE_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BESOEGSSTATUS_DIM(
   BESOEGSSTATUS_DIM int NOT NULL PRIMARY KEY
  ,BESOEGSSTATUS_KODENR nvarchar(10)
  ,BESOEGSSTATUS_KODEVAERDI nvarchar(50)
  ,BESOEGSSTATUS_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BRANCHE_ARBMILJOERAAD_DIM(
   BRANCHE_ARBMILJOERAAD_DIM int NOT NULL PRIMARY KEY
  ,BAR_DB07_KODENR_1 nvarchar(10)
  ,BAR_DB07_KODEVAERDI_1 nvarchar(10)
  ,BAR_DB07_TEKST_1 nvarchar(50)
  ,BAR_DB07_CONCAT_1 nvarchar(50)
  ,DB07_KODENR_2 nvarchar(10)
  ,DB07_KODEVAERDI_2 nvarchar(10)
  ,DB07_TEKST_2 nvarchar(100)
  ,DB07_CONCAT_2 nvarchar(100)
  ,DB07_LANGTEKST_2 nvarchar(250)
  ,DB07_KODEVAERDI_OG_LANGTEKST_2 nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BRANCHE_DB07_DIM(
   BRANCHE_DB07_DIM int NOT NULL PRIMARY KEY
  ,BRANCHEG10_DB07_KLBE_IDENT_0 nvarchar(20)
  ,BRANCHEG10_DB07_KODENR_0 nvarchar(10)
  ,BRANCHEG10_DB07_KODEVAERDI_0 nvarchar(10)
  ,BRANCHEG10_DB07_TEKST_0 nvarchar(50)
  ,BRANCHEG10_DB07_CONCAT_0 nvarchar(50)
  ,BRANCHEGRP_DB07_KLBE_IDENT_1 nvarchar(20)
  ,BRANCHEGRP_DB07_KODENR_1 nvarchar(10)
  ,BRANCHEGRP_DB07_KODEVAERDI_1 nvarchar(10)
  ,BRANCHEGRP_DB07_TEKST_1 nvarchar(100)
  ,BRANCHEGRP_DB07_CONCAT_1 nvarchar(100)
  ,DB07_KLBE_IDENT_2 nvarchar(10)
  ,DB07_KODENR_2 nvarchar(10)
  ,DB07_KODEVAERDI_2 nvarchar(10)
  ,DB07_TEKST_2 nvarchar(100)
  ,DB07_CONCAT_2 nvarchar(100)
  ,DB07_LANGTEKST_2 nvarchar(250)
  ,DB07_KODEVAERDI_OG_LANGTEKST_2 nvarchar(250)
  ,TILSYNSGRUPPE_NR int
  ,TILSYNSGRUPPE_NAVN nvarchar(10)
  ,TILSYNSGRUPPE_CONCAT nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BRANCHE_HGRP_DIM(
   BRANCHE_HGRP_DIM int NOT NULL PRIMARY KEY
  ,BRANCHE_HGRP_KODENR nvarchar(10)
  ,BRANCHE_HGRP_KODEVAERDI nvarchar(50)
  ,BRANCHE_HGRP_TEKST nvarchar(100)
  ,BRANCHE_HGRP_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BRANCHE_NACE_DIM(
   BRANCHE_NACE_DIM int NOT NULL PRIMARY KEY
  ,BRANCHE_HGRP_KODENR_0 nvarchar(10)
  ,BRANCHE_HGRP_KODEVAERDI_0 nvarchar(20)
  ,BRANCHE_HGRP_TEKST_0 nvarchar(100)
  ,BRANCHE_HGRP_CONCAT_0 nvarchar(100)
  ,BRANCHEG10_DB07_KODENR_0 nvarchar(10)
  ,BRANCHEG10_DB07_KODEVAERDI_0 nvarchar(10)
  ,BRANCHEG10_DB07_TEKST_0 nvarchar(50)
  ,BRANCHEG10_DB07_CONCAT_0 nvarchar(50)
  ,BRANCHEGRP_DB07_KODENR_1 nvarchar(10)
  ,BRANCHEGRP_DB07_KODEVAERDI_1 nvarchar(10)
  ,BRANCHEGRP_DB07_TEKST_1 nvarchar(100)
  ,BRANCHEGRP_DB07_CONCAT_1 nvarchar(100)
  ,NACE_KODE_KODENR_2 nvarchar(10)
  ,NACE_KODE_KODEVAERDI_2 nvarchar(10)
  ,NACE_KODE_TEKST_2 nvarchar(100)
  ,NACE_KODE_CONCAT_2 nvarchar(100)
  ,NACE_LANGTEKST_2 nvarchar(250)
  ,NACE_KODEVAERDI_OG_LANGTEKST_2 nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.BYGGEPLADS_DIM(
   BYGGEPLADS_DIM int NOT NULL PRIMARY KEY
  ,INR int
  ,BYGGEPLADS_NAVN nvarchar(250)
  ,ADRESSE nvarchar(250)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,PRODENHED_NR bigint
  ,PRODENHED_NAVN nvarchar(250)
  ,JURIDISK_ENHED_CVRNR int
  ,JURIDISK_ENHED_NAVN nvarchar(250)
  ,ATVIRK_ANR int
  ,ATVIRK_NAVN nvarchar(100)
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,KOORDINERINGSCENTER_NR int
  ,KOORDINERINGSCENTER_NAVN nvarchar(50)
  ,STATUS int
  ,STATUS_TEKST nvarchar(20)
  ,FORV_START_DATO datetime
  ,FORV_SLUT_DATO datetime
  ,FORV_ANTAL_ANSATTE int
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.DIAGNOSE_DIM(
   DIAGNOSE_DIM int NOT NULL PRIMARY KEY
  ,DIAGNOSE_KLASSIFIKATION_ID_1 nvarchar(10)
  ,DIAGNOSE_KODE_1 nvarchar(10)
  ,DIAGNOSE_NAVN_1 nvarchar(250)
  ,DIAGNOSE_CONCAT_1 nvarchar(250)
  ,DIAGNOSE_KLASSIFIKATION_ID_2 nvarchar(10)
  ,DIAGNOSE_KODE_2 nvarchar(10)
  ,DIAGNOSE_NAVN_2 nvarchar(250)
  ,DIAGNOSE_CONCAT_2 nvarchar(250)
  ,DIAGNOSE_KLASSIFIKATION_ID_3 nvarchar(10)
  ,DIAGNOSE_KODE_3 nvarchar(10)
  ,DIAGNOSE_NAVN_3 nvarchar(100)
  ,DIAGNOSE_CONCAT_3 nvarchar(100)
  ,DIAGNOSE_KLASSIFIKATION_ID_4 nvarchar(10)
  ,DIAGNOSE_KODE_4 nvarchar(10)
  ,DIAGNOSE_NAVN_4 nvarchar(100)
  ,DIAGNOSE_CONCAT_4 nvarchar(100)
  ,DIAGNOSE_KLASSIFIKATION_ID nvarchar(10)
  ,DIAGNOSE_KODE nvarchar(10)
  ,DIAGNOSE_NAVN nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.DIAGNOSE_HT08_DIM(
   DIAGNOSE_HT08_DIM int NOT NULL PRIMARY KEY
  ,DIAGNOSE_HT08_KODE_1 nvarchar(10)
  ,DIAGNOSE_HT08_NAVN_1 nvarchar(50)
  ,DIAGNOSE_HT08_SORT_1 nvarchar(10)
  ,DIAGNOSE_HT08_CONCAT_1 nvarchar(50)
  ,DIAGNOSE_HT08_KODE_2 nvarchar(10)
  ,DIAGNOSE_HT08_NAVN_2 nvarchar(10)
  ,DIAGNOSE_HT08_SORT_2 nvarchar(10)
  ,DIAGNOSE_HT08_CONCAT_2 nvarchar(10)
  ,DIAGNOSE_HT08_KODE nvarchar(10)
  ,DIAGNOSE_HT08_NAVN nvarchar(100)
  ,DIAGNOSE_HT08_SORT nvarchar(10)
  ,DIAGNOSE_HT08_CONCAT nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_AFVIGELSE_E5(
   DIM_AFVIGELSE_E5 int
  ,AFVIGELSE_NR_1 nvarchar(10)
  ,AFVIGELSE_NAVN_1 nvarchar(100)
  ,AFVIGELSE_NR_NAVN_1 nvarchar(100)
  ,AFVIGELSE_NR_2 nvarchar(10)
  ,AFVIGELSE_NAVN_2 nvarchar(250)
  ,AFVIGELSE_NR_NAVN_2 nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_AFVISNINGSGRUND(
   DIM_AFVISNINGSGRUND int
  ,AFVISNINGSGRUND_NAVN nvarchar(50)
  ,AFVISNINGSGRUND_NR int
  ,AFVISNINGSGRUND_NR_NAVN nvarchar(50)
  ,AFVISNINGSGRUND_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ANSAETTELSESFORM(
   DIM_ANSAETTELSESFORM int
  ,ANSAETTELSESFORM_NR nvarchar(10)
  ,ANSAETTELSESFORM_NAVN nvarchar(50)
  ,ANSAETTELSESFORM_NR_NAVN nvarchar(50)
  ,ANSAETTELSESFORM_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ANSAETTELSESFORM_E5(
   DIM_ANSAETTELSESFORM_E5 int
  ,ANSAETTELSESFORM_ID_1 nvarchar(10)
  ,ANSAETTELSESFORM_NR_1 nvarchar(10)
  ,ANSAETTELSESFORM_NAVN_1 nvarchar(50)
  ,ANSAETTELSESFORM_NR_NAVN_1 nvarchar(50)
  ,ANSAETTELSESFORM_NR_2 nvarchar(10)
  ,ANSAETTELSESFORM_NAVN_2 nvarchar(100)
  ,ANSAETTELSESFORM_NR_NAVN_2 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_BESOEG_VIRK_FAMILIE(
   DIM_BESOEG_VIRK_FAMILIE int
  ,BESOEG_VIRK_FAMILIE_KODE int
  ,BESOEG_VIRK_FAMILIE_TEKST nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_BRANCHE_FAELLESSKAB(
   DIM_BRANCHE_FAELLESSKAB int
  ,BFA_DB07_NR nvarchar(10)
  ,BFA_DB07_NAVN nvarchar(100)
  ,BFA_DB07_NR_NAVN nvarchar(100)
  ,DB07_NR nvarchar(10)
  ,DB07_NAVN nvarchar(250)
  ,DB07_NR_NAVN nvarchar(250)
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
)
GO
CREATE TABLE DMSA.DIM_FRISTSTATUS(
   DIM_FRISTSTATUS int
  ,FRISTSTATUS_KODENR int
  ,FRISTSTATUS_KODEVAERDI nvarchar(20)
  ,FRISTSTATUS_TEKST nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_FRISTTYPE(
   DIM_FRISTTYPE int
  ,FRISTTYPE_KODENR int
  ,FRISTTYPE_KODEVAERDI nvarchar(50)
  ,FRISTTYPE_TEKST nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_GEOGRAFI(
   DIM_GEOGRAFI int
  ,REGION_NR int
  ,REGION_NAVN nvarchar(50)
  ,KOMMUNE_NR int
  ,KOMMUNE_NAVN nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_JOBTYPE(
   DIM_JOBTYPE int
  ,JOBTYPE_NR_1 nvarchar(10)
  ,JOBTYPE_NAVN_1 nvarchar(100)
  ,JOBTYPE_NR_NAVN_1 nvarchar(100)
  ,JOBTYPE_SORT_1 int
  ,JOBTYPE_NR_2 nvarchar(10)
  ,JOBTYPE_NAVN_2 nvarchar(250)
  ,JOBTYPE_NR_NAVN_2 nvarchar(250)
  ,JOBTYPE_SORT_2 int
  ,JOBTYPE_NR_3 nvarchar(10)
  ,JOBTYPE_NAVN_3 nvarchar(250)
  ,JOBTYPE_NR_NAVN_3 nvarchar(250)
  ,JOBTYPE_SORT_3 int
  ,JOBTYPE_NR_4 nvarchar(10)
  ,JOBTYPE_NAVN_4 nvarchar(250)
  ,JOBTYPE_NR_NAVN_4 nvarchar(250)
  ,JOBTYPE_SORT_4 int
  ,JOBTYPE_NR_5 nvarchar(10)
  ,JOBTYPE_NAVN_5 nvarchar(250)
  ,JOBTYPE_NR_NAVN_5 nvarchar(250)
  ,JOBTYPE_SORT_5 int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_JOBTYPE_E5(
   DIM_JOBTYPE_E5 int
  ,JOBTYPE_NR_1 nvarchar(10)
  ,JOBTYPE_NAVN_1 nvarchar(100)
  ,JOBTYPE_NR_NAVN_1 nvarchar(100)
  ,JOBTYPE_NR_2 nvarchar(10)
  ,JOBTYPE_NAVN_2 nvarchar(250)
  ,JOBTYPE_NR_NAVN_2 nvarchar(250)
  ,JOBTYPE_NR_3 nvarchar(10)
  ,JOBTYPE_NAVN_3 nvarchar(250)
  ,JOBTYPE_NR_NAVN_3 nvarchar(250)
  ,JOBTYPE_NR_4 nvarchar(10)
  ,JOBTYPE_NAVN_4 nvarchar(250)
  ,JOBTYPE_NR_NAVN_4 nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_KOEN(
   DIM_KOEN int
  ,KOEN_KODE nvarchar(1)
  ,KOEN_TEKST nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_KVOTERINGSPULJE(
   DIM_KVOTERINGSPULJE int
  ,KVOTERINGSPULJE_NR int
  ,KVOTERINGSPULJE_NAVN nvarchar(10)
  ,KVOTERINGSPULJE_SORT int
  ,KVOTERINGSPULJE_NR_NAVN nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_KVOTERINGSSTATUS(
   DIM_KVOTERINGSSTATUS int
  ,KVOTERINGSSTATUS_NR int
  ,KVOTERINGSSTATUS_NAVN nvarchar(50)
  ,KVOTERINGSSTATUS_NR_NAVN nvarchar(50)
  ,KVOTERINGSSTATUS_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_MT_REG_KATEGORI(
   DIM_KONTOPLAN int NOT NULL
  ,MT_REG_KATEGORI_NAVN nvarchar(50)
  ,MT_REG_KATEGORI_NR int
  ,MT_REG_KATEGORI_NR_OG_NAVN nvarchar(50)
  ,NIVEAU2_NR_OG_NAVN nvarchar(100)
  ,NIVEAU2_NR nvarchar(20)
  ,NIVEAU2_NAVN nvarchar(100)
)
GO
CREATE TABLE DMSA.DIM_PLANLAEGNINGSENHED(
   DIM_PLANLAEGNINGSENHED int
  ,PLANLAEGNINGSENHED_ID int
  ,AT_NAVN nvarchar(10)
  ,TC_NAVN nvarchar(50)
  ,TG_NAVN nvarchar(50)
  ,US_NAVN nvarchar(20)
  ,TG_US_NAVN nvarchar(100)
  ,AT_NR int
  ,TC_ID int
  ,TG_ID int
  ,US_ID int
  ,DWH_FROM_DATE date
  ,DWH_TO_DATE date
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
  ,TG_US_ID nvarchar(10)
)
GO
CREATE TABLE DMSA.DIM_SKADEMAADE(
   DIM_SKADEMAADE int
  ,SKADEMAADE_NR_1 nvarchar(10)
  ,SKADEMAADE_NAVN_1 nvarchar(100)
  ,SKADEMAADE_NR_NAVN_1 nvarchar(100)
  ,SKADEMAADE_SORT_1 int
  ,SKADEMAADE_NR_2 nvarchar(10)
  ,SKADEMAADE_NAVN_2 nvarchar(250)
  ,SKADEMAADE_NR_NAVN_2 nvarchar(250)
  ,SKADEMAADE_SORT_2 int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADEMAADE_E5(
   DIM_SKADEMAADE_E5 int
  ,SKADEMAADE_NR_1 nvarchar(10)
  ,SKADEMAADE_NAVN_1 nvarchar(100)
  ,SKADEMAADE_NR_NAVN_1 nvarchar(100)
  ,SKADEMAADE_NR_2 nvarchar(10)
  ,SKADEMAADE_NAVN_2 nvarchar(100)
  ,SKADEMAADE_NR_NAVN_2 nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADENS_ART(
   DIM_SKADENS_ART int
  ,SKADENS_ART_NR nvarchar(10)
  ,SKADENS_ART_NAVN nvarchar(100)
  ,SKADENS_ART_NR_NAVN nvarchar(100)
  ,SKADENS_ART_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADENS_ART_E5(
   DIM_SKADENS_ART_E5 int
  ,SKADENS_ART_NR_1 nvarchar(10)
  ,SKADENS_ART_NAVN_1 nvarchar(100)
  ,SKADENS_ART_NR_NAVN_1 nvarchar(100)
  ,SKADENS_ART_NR_2 nvarchar(10)
  ,SKADENS_ART_NAVN_2 nvarchar(250)
  ,SKADENS_ART_NR_NAVN_2 nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADENS_FOELGER(
   DIM_SKADENS_FOELGER int
  ,SKADENS_FOELGER_NR nvarchar(10)
  ,SKADENS_FOELGER_NAVN nvarchar(50)
  ,SKADENS_FOELGER_NR_NAVN nvarchar(50)
  ,SKADENS_FOELGER_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADENS_FOELGER_E5(
   DIM_SKADENS_FOELGER_E5 int
  ,SKADENS_FOELGER_NR nvarchar(10)
  ,SKADENS_FOELGER_NAVN nvarchar(100)
  ,SKADENS_FOELGER_NR_NAVN nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADETYPE(
   DIM_SKADETYPE int
  ,SKADETYPE_NR nvarchar(10)
  ,SKADETYPE_NAVN nvarchar(50)
  ,SKADETYPE_NR_NAVN nvarchar(100)
  ,SKADETYPE_NR_GRP_1 nvarchar(10)
  ,SKADETYPE_NAVN_GRP_1 nvarchar(50)
  ,SKADETYPE_NR_NAVN_GRP_1 nvarchar(50)
  ,SKADETYPE_NR_GRP_2 nvarchar(10)
  ,SKADETYPE_NAVN_GRP_2 nvarchar(20)
  ,SKADETYPE_NR_NAVN_GRP_2 nvarchar(50)
  ,SKADETYPE_NR_GRP_3 nvarchar(10)
  ,SKADETYPE_NAVN_GRP_3 nvarchar(50)
  ,SKADETYPE_NR_NAVN_GRP_3 nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
  ,SKADETYPE_SORT int
  ,SKADETYPE_SORT_GRP_1 int
  ,SKADETYPE_SORT_GRP_2 int
  ,SKADETYPE_SORT_GRP_3 int
)
GO
CREATE TABLE DMSA.DIM_SKADET_LEGEMSDEL(
   DIM_SKADET_LEGEMSDEL int
  ,SKADET_LEGEMSDEL_NR nvarchar(10)
  ,SKADET_LEGEMSDEL_NAVN nvarchar(250)
  ,SKADET_LEGEMSDEL_NR_NAVN nvarchar(250)
  ,SKADET_LEGEMSDEL_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_SKADET_LEGEMSDEL_E5(
   DIM_SKADET_LEGEMSDEL_E5 int
  ,SKADET_LEGEMSDEL_NR_1 nvarchar(10)
  ,SKADET_LEGEMSDEL_NAVN_1 nvarchar(100)
  ,SKADET_LEGEMSDEL_NR_NAVN_1 nvarchar(100)
  ,SKADET_LEGEMSDEL_NR_2 nvarchar(10)
  ,SKADET_LEGEMSDEL_NAVN_2 nvarchar(100)
  ,SKADET_LEGEMSDEL_NR_NAVN_2 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_STATSBORGERSKAB(
   DIM_STATSBORGERSKAB int
  ,STATSBORGERSKAB_NR nvarchar(10)
  ,STATSBORGERSKAB_NAVN nvarchar(250)
  ,STATSBORGERSKAB_NR_NAVN nvarchar(250)
  ,STATSBORGERSKAB_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_TEKNIK(
   DIM_TEKNIK int
  ,TEKNIK_NR_GRP_1 nvarchar(10)
  ,TEKNIK_NAVN_GRP_1 nvarchar(100)
  ,TEKNIK_NR_NAVN_GRP_1 nvarchar(100)
  ,TEKNIK_SORT_GRP_1 int
  ,TEKNIK_NR nvarchar(10)
  ,TEKNIK_NAVN nvarchar(250)
  ,TEKNIK_NR_NAVN nvarchar(250)
  ,TEKNIK_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_TILSYNF_STATUS_GROVP(
   DIM_TILSYNF_STATUS_GROVP int NOT NULL PRIMARY KEY
  ,TILSYNF_STATUS_GROVP_NAVN nvarchar(10)
  ,TILSYNF_STATUS_GROVP_BESKRIV nvarchar(10)
  ,DWH_IS_ACTIVE nvarchar(4000)
  ,DWH_HUB_SEQ int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_UDKOERSELSSTED(
   DIM_UDKOERSELSSTED int NOT NULL PRIMARY KEY
  ,US_KODE int
  ,US_NAVN nvarchar(20)
  ,KOMMUNE_GRP_KODE int
  ,KOMMUNE_GRP_NAVN nvarchar(20)
  ,KOMMUNE_KODE int
  ,KOMMUNE_NAVN nvarchar(50)
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
)
GO
CREATE TABLE DMSA.DIM_ULYKKESSTED(
   DIM_ULYKKESSTED int
  ,ULYKKESSTED_NR nvarchar(10)
  ,ULYKKESSTED_NAVN nvarchar(250)
  ,ULYKKESSTED_NR_NAVN nvarchar(250)
  ,ULYKKESSTED_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ULYKKESSTED_E5(
   DIM_ULYKKESSTED_E5 int
  ,ULYKKESSTED_NR int
  ,ULYKKESSTED_NAVN nvarchar(250)
  ,ULYKKESSTED_NR_NAVN nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ULYKKE_ALDER(
   DIM_ULYKKE_ALDER int
  ,ULYKKE_ALDER_NR_1 nvarchar(10)
  ,ULYKKE_ALDER_NAVN_1 nvarchar(20)
  ,ULYKKE_ALDER_SORT_1 int
  ,ULYKKE_ALDER_NR_2 nvarchar(10)
  ,ULYKKE_ALDER_NAVN_2 nvarchar(20)
  ,ULYKKE_ALDER_SORT_2 int
  ,ULYKKE_ALDER_NR_3 nvarchar(10)
  ,ULYKKE_ALDER_SORT_3 int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ULYKKE_ANMELDERTYPE(
   DIM_ULYKKE_ANMELDERTYPE int
  ,ULYKKE_ANMELDERTYPE_NR nvarchar(10)
  ,ULYKKE_ANMELDERTYPE_NAVN nvarchar(100)
  ,ULYKKE_ANMELDERTYPE_NR_NAVN nvarchar(100)
  ,ULYKKE_ANMELDERTYPE_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ULYKKE_ANMELDERTYPE_E5(
   DIM_ULYKKE_ANMELDERTYPE_E5 int
  ,ANMELDERTYPE_NR_1 nvarchar(10)
  ,ANMELDERTYPE_NAVN_1 nvarchar(50)
  ,ANMELDERTYPE_NR_NAVN_1 nvarchar(50)
  ,ANMELDERTYPE_NR_2 nvarchar(10)
  ,ANMELDERTYPE_NAVN_2 nvarchar(100)
  ,ANMELDERTYPE_NR_NAVN_2 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_ULYKKE_KILDE(
   DIM_ULYKKE_KILDE int
  ,ULYKKE_KILDE_NAVN nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DIM_VOLD(
   DIM_VOLD int
  ,VOLD_NR nvarchar(10)
  ,VOLD_NAVN nvarchar(250)
  ,VOLD_NR_NAVN nvarchar(250)
  ,VOLD_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.DISCO_DIM(
   DISCO_DIM int NOT NULL PRIMARY KEY
  ,DISCO_KODENR_1 nvarchar(10)
  ,DISCO_KODEVAERDI_1 nvarchar(10)
  ,DISCO_TEKST_1 nvarchar(50)
  ,DISCO_CONCAT_1 nvarchar(100)
  ,DISCO_KODENR_2 nvarchar(10)
  ,DISCO_KODEVAERDI_2 nvarchar(10)
  ,DISCO_TEKST_2 nvarchar(50)
  ,DISCO_CONCAT_2 nvarchar(100)
  ,DISCO_KODENR_3 nvarchar(10)
  ,DISCO_KODEVAERDI_3 nvarchar(10)
  ,DISCO_TEKST_3 nvarchar(50)
  ,DISCO_CONCAT_3 nvarchar(100)
  ,DISCO_KODENR_4 nvarchar(10)
  ,DISCO_KODEVAERDI_4 nvarchar(10)
  ,DISCO_TEKST_4 nvarchar(50)
  ,DISCO_CONCAT_4 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.ENHEDSTYPE_DIM(
   ENHEDSTYPE_DIM int NOT NULL PRIMARY KEY
  ,ENHEDSTYPE_KODE nvarchar(10)
  ,ENHEDSTYPE_NAVN nvarchar(20)
  ,ENHEDSTYPE_SORT nvarchar(10)
  ,ENHEDSTYPE_CONCAT nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.ESS_KILDE_DIM(
   ESS_KILDE_DIM int NOT NULL PRIMARY KEY
  ,KILDE nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_AFRAPPORTERING_AF_RT(
   TID_DIM int
  ,GEOGRAFI_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,OPGIVELSE_AF_RT_DIM int
  ,FORSOEG_BESOEGT_DIM int
  ,FORSOEGT_BESOEGT_JN_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,BELIGGENHEDSCENTER_DIM int
  ,VARSLING_STATUS_DIM int
  ,RESULTAT_AF_RT_DIM int
  ,VARSL_STATUS_PRODENH_DIM int
  ,B_CENTER_BS_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,B_CENTER_P_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,SAGSNUMMER bigint
  ,BESOEGSNR int
  ,ENHEDSNR bigint
  ,ANTAL_RT int
  ,ANTAL_MATERIEL_AFG int
  ,ANTAL_VEJL_PSYK int
  ,ANTAL_MAT_AFG_OG_VEJL_PSYK int
  ,ANTAL_FORMEL_AFG int
  ,ANTAL_INGEN_AFG int
  ,ANTAL_OPGIVET int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
  ,DIM_PLANLAEGNINGSENHED int
  ,DIM_TID_VARSLINGSDATO int
  ,DIM_JN_DIGITAL_VARSEL_P int
  ,DIM_JN_MSA_BESOEG int
)
GO
CREATE TABLE DMSA.FACT_ANMELDELSE(
   TID_DIM int
  ,GEOGRAFI_DIM int
  ,LOKATION_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,SOC_DUMP_ANMELDERTYPE_DIM int
  ,ANTAL_ANMELDELSER int
  ,ANTAL_ANMELDTE_VIRKSOMHEDER int
  ,ANTAL_ANMELDTE_LOKATIONER int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.FACT_BESOEG(
   TID_DIM int
  ,TIDSVINDUE_START_TID_DIM int
  ,TIDSVINDUE_SLUT_TID_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,ATVIRK_DIM int
  ,BYGGEPLADS_DIM int
  ,LOKATION_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,BESOEGSSTATUS_DIM int
  ,BESOEGSROLLE_DIM int
  ,AFLYSNING_DIM int
  ,FORSOEGT_BESOEGT_DIM int
  ,TILSYNSFORM_DIM int
  ,SUNDHEDSFREMME_JN_DIM int
  ,MEDARBEJDER_DIM int
  ,BESOEGSNR int
  ,ENHEDSTYPE_DIM int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_B_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,BELIGGENHEDSCENTER_DIM int
  ,GEOGRAFI_DIM int
  ,ENHEDSNR bigint
  ,ANTAL_BESOEGSNR int
  ,ANTAL_PLANLAEGNINGSBESOEG int
  ,ANTAL_BESOEG_AFLYSTE int
  ,ANTAL_BESOEG_FORSOEGT_BESOEGT int
  ,ANTAL_TILSYNSBESOEG int
  ,ANTAL_MEDARBEJDERBESOEG int
  ,ANTAL_DOBBELTBESOEG int
  ,ANTAL_BESOEGSREGISTRERINGER int
  ,ANTAL_VIRKSOMHEDSBESOEG int
  ,ANTAL_BYGGEPLADSBESOEG int
  ,ANTAL_BESOEGSTIMER float
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
  ,DIM_TID_VARSLINGSDATO int
)
GO
CREATE TABLE DMSA.FACT_ERHVERVSSYGDOMME(
   TID_DIM int
  ,PAAVIRKNING_FRA_TID_DIM int
  ,PAAVIRKNING_TIL_TID_DIM int
  ,PAAVIRKNING_NY_JN_DIM int
  ,PERSON_DIM int
  ,LOENMODTAGER_JN_DIM int
  ,GENOPTAGET_ARBEJDE_JN_DIM int
  ,ALDER_DIM int
  ,STILLING_DIM int
  ,DIAGNOSE_DIM int
  ,DIAGNOSE_HT08_DIM int
  ,LEGEMSDEL_DIM int
  ,LEGEMSDEL_GRP_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,ANTAL_ANSATTE_2_DIM int
  ,JURIDISK_ENHED_DIM_ARBGIV bigint
  ,NUVAERENDE_ARBEJDSGIVER_JN_DIM int
  ,ER_PAAVIRKNINGSSTED char(4)
  ,BRANCHE_DB07_DIM int
  ,BRANCHE_ARBMILJOERAAD_DIM int
  ,BRANCHE_NACE_DIM int
  ,NACE_38_DIM int
  ,JURIDISK_ENHED_DIM_ANMELD bigint
  ,ANMELDERTYPE_DIM int
  ,ER_HONORARBERETTIGET char(4)
  ,PAAVIRKNING_DIM int
  ,PAAVIRKNING_GRP_DIM int
  ,PAAVIRKNING_DIM_1 int
  ,PAAVIRKNING_GRP_DIM_1 int
  ,PAAVIRKNING_DIM_2 int
  ,PAAVIRKNING_GRP_DIM_2 int
  ,PAAVIRKNING_DIM_3 int
  ,PAAVIRKNING_GRP_DIM_3 int
  ,BELIGGENHEDSCENTER_DIM int
  ,GEOGRAFI_DIM int
  ,ESS_KILDE_DIM int
  ,KEMISKE_SYGDOMME_JN_DIM int
  ,MYNDIGHED_DIM int
  ,ANTAL_ANMELDELSER int
  ,ANTAL_ANMELDELSER_DEDUP int
  ,ANTAL_PAAVIRKNINGER int
  ,ANTAL_PAAVIRKNINGER_DEDUP int
  ,ANTAL_PAAVIRKNINGER_ALLE_ANM int
  ,ANTAL_OPHOBNINGER int
  ,ANTAL_KEMISKE_SYGDOMME int
  ,MAA_VISES_AT char(4)
  ,EASYNR nvarchar(10)
  ,ARBEJDSGIVER_KODE nvarchar(20)
  ,STILLINGSBETEGNELSE nvarchar(250)
  ,BESKRIVELSE_AF_ARB nvarchar(4000)
  ,REG_FIRMANAVN nvarchar(100)
  ,REG_ARBEJDSSTEDNAVN nvarchar(100)
  ,REG_VEJNAVN nvarchar(250)
  ,REG_HUSNR nvarchar(50)
  ,REG_POSTNR nvarchar(20)
  ,REG_BYNAVN nvarchar(250)
  ,REG_LAND nvarchar(50)
  ,DIM_BRANCHE_DB07_J_ANMELD int
  ,DIM_B_CENTER_J_ANMELD int
  ,DIM_GEOGRAFI_J_ANMELD int
  ,DIM_B_CENTER_J_ARBGIV int
  ,DIM_BRANCHE_DB07_J_ARBGIV int
  ,DIM_GEOGRAFI_J_ARBGIV int
  ,DIM_B_CENTER_P int
  ,DIM_BRANCHE_DB07_P int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,DIM_BRANCHE_TG_P int
  ,DIM_GEOGRAFI_P int
  ,DIM_BRANCHE_FAELLESSKAB int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_LIDELSER(
   LBNREASY int
  ,ANTAL_PAAVIRKNINGER int
  ,ANTAL_ANMELDELSER int
  ,ALDER_DIM int
  ,TID_DIM int
  ,PAAVIRKNING_FRA_TID_DIM int
  ,PAAVIRKNING_TIL_TID_DIM int
  ,DIAGNOSE_DIM int
  ,DIAGNOSE_HT08_DIM int
  ,LEGEMSDEL_DIM int
  ,LEGEMSDEL_GRP_DIM int
  ,PAAVIRKNING_DIM int
  ,PAAVIRKNING_GRP_DIM int
  ,PAAVIRKNING_DIM_1 int
  ,PAAVIRKNING_GRP_DIM_1 int
  ,PAAVIRKNING_DIM_2 int
  ,PAAVIRKNING_GRP_DIM_2 int
  ,PAAVIRKNING_DIM_3 int
  ,PAAVIRKNING_GRP_DIM_3 int
  ,BRANCHE_DB07_DIM int
  ,BRANCHE_ARBMILJOERAAD_DIM int
  ,GEOGRAFI_DIM int
  ,BELIGGENHEDSCENTER_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,JURIDISK_ENHED_DIM bigint
  ,ANMELDER_JURIDISK_ENHED_DIM bigint
  ,ANMELDERTYPE_DIM int
  ,LOENMODTAGER_JN_DIM int
  ,ESS_KILDE_DIM int
  ,PERSON_DIM int
  ,DISCO_DIM int
  ,FIRMANAVN nvarchar(250)
  ,BESKRIVELSE nvarchar(4000)
  ,BRANCE_NACE_DIM int
  ,ANTAL_ANSATTE_2_DIM int
  ,NACE_38_DIM int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_LOKATIONER_BESOEG(
   BESOEG_TID_DIM int
  ,FRIST_START_TID_DIM int
  ,FRIST_SLUT_TID_DIM int
  ,OPRET_TID_DIM int
  ,LOKATION_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,AARSAGER_DIM int
  ,GEOGRAFI_DIM int
  ,BESOEGSSTATUS_DIM int
  ,AFLYSNING_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,FRIST_OVERKREDET_JN_DIM int
  ,BESOEGT_FOER_RUT_OPRET_JN_DIM int
  ,BESOEGSNR int
  ,ANTAL_LOKATIONER_UDTAGET int
  ,ANTAL_LOKATIONER_BESOEGT int
  ,ANTAL_LOK_FORSOEGT_BESOEGT int
  ,ANTAL_LOKATIONER_AFLYST int
  ,ANTAL_RUT_FRISTER_OVERSKRED int
  ,ANTAL_ATDK_FRISTER_OVERSKRED int
  ,ANTAL_PLANLAEGNINGSBESOEG int
  ,ANTAL_LOKATIONSBESOEG int
  ,ANTAL_LOKATIONSBESOEG_AFLYST int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_NORMTID(
   DIM_MEDARBEJDER int
  ,DIM_ORG_ENHED int
  ,DIM_TID int
  ,AD_NR nvarchar(10)
  ,DATO_ARBEJDSDAG int
  ,NORMTID float
  ,FULDTIDSNORM float
  ,STANDARD_FULDTIDSNORM float
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
)
GO
CREATE TABLE DMSA.FACT_RAADGIVNINGSPAABUD(
   AFSENDT_RP_TID_DIM int
  ,AKTNUMMER_RP bigint
  ,ANTAL int
  ,ATVIRK_DIM int
  ,DOKUMENTNR_RP bigint
  ,ENHEDSTYPE_DIM int
  ,BESOEG_PAA_ENHEDSTYPE_DIM int
  ,GEOGRAFI_DIM int
  ,KONSTATERING_TID_DIM int
  ,LOKATION_DIM int
  ,MEDARBEJDER_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,SAGSNUMMER bigint
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_J_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,BESOEGSNR int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_J_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,DIM_GEOGRAFI_BS int
  ,DIM_GEOGRAFI_A int
  ,DIM_GEOGRAFI_J int
  ,DIM_GEOGRAFI_L int
  ,DIM_GEOGRAFI_P int
  ,JURIDISK_ENHED_DIM bigint
  ,ORG_ENHED_DIM int
  ,REAKTION_RP_DIM int
  ,TILSYNSAKTIVITET_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
)
GO
CREATE TABLE DMSA.FACT_RAADGIVNINGSPAABUD_AMP(
   AFSENDT_RP_TID_DIM int
  ,AKTNUMMER_RP bigint
  ,AKTNUMMER_REAK bigint
  ,ANTAL_REAK int
  ,ARBEJDSMILJOEPROBLEM_DIM int
  ,ATVIRK_DIM int
  ,BESOEGSNR int
  ,DIM_GEOGRAFI_BS int
  ,DIM_GEOGRAFI_A int
  ,DIM_GEOGRAFI_J int
  ,DIM_GEOGRAFI_L int
  ,DIM_GEOGRAFI_P int
  ,DOKUMENTNR_RP bigint
  ,DOKUMENTNR_REAK bigint
  ,REAK_ENHEDSTYPE_DIM int
  ,BESOEG_PAA_ENHEDSTYPE_DIM int
  ,AARSAGER_DIM int
  ,GEOGRAFI_DIM int
  ,DATO_BESOEG_TID_DIM int
  ,LOKATION_DIM int
  ,MEDARBEJDER_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,REAK_REAKTION_DIM int
  ,SAGSNUMMER bigint
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,AFSENDT_REAK_TID_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_J_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_J_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,JURIDISK_ENHED_DIM bigint
  ,ORG_ENHED_DIM int
  ,RP_REAKTION_DIM int
  ,TILSYNSAKTIVITET_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
)
GO
CREATE TABLE DMSA.FACT_REAKTIONSFRISTER(
   AKTNUMMER bigint NOT NULL PRIMARY KEY
  ,SAGSNUMMER bigint NOT NULL
  ,REAKTIONS_ID int
  ,DOKUMENTNR bigint NOT NULL
  ,BESOEGSNR int NOT NULL
  ,SAGSTYPE_DIM int
  ,AKTTYPE_DIM int NOT NULL
  ,B_CENTER_BS_DIM int NOT NULL
  ,ORG_ENHED_DIM int
  ,MEDARBEJDER_DIM int NOT NULL
  ,START_BEHANDLING_TID_DIM int NOT NULL
  ,SLUT_BEHANDLING_TID_DIM int NOT NULL
  ,ANTAL_AKTER int NOT NULL
  ,ANTAL_DAGE int
  ,FRIST_OVERSKREDET_JN_DIM int NOT NULL
  ,DWH_LOAD_DATE date NOT NULL
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_RESULTATKRAV(
   TID_DIM int
  ,B_CENTER_BS_DIM int
  ,ORG_ENHED_DIM_ANSV_TIMER int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,MEDARBEJDER_DIM int
  ,KONTOPLAN_DIM int
  ,TILSYNSAKTIVITET_DIM int
  ,PERIODETYPE nvarchar(10)
  ,KLASS_4_DIM float
  ,KLASS_5_DIM float
  ,KRAVTYPE nvarchar(50)
  ,MAALEENHED nvarchar(10)
  ,ANTAL_KRAV int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_TIDSREGISTRERING(
   TID_DIM int
  ,KONTOPLAN_DIM int
  ,MEDARBEJDER_DIM int
  ,ORG_ENHED_DIM int
  ,ANTAL_TIMER float
  ,ANTAL_VIRKSOMHEDSTIMER float
  ,NORMTID float
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_TILBAGEMELDINGER(
   AKTNUMMER bigint
  ,AKTNUMMER_SVAR bigint
  ,DOKUMENTNR bigint
  ,DOKUMENTNR_SVAR bigint
  ,SAGSNUMMER bigint
  ,BESOEGSNR int
  ,ANTAL_TILBAGEMELDINGER int
  ,ANTAL_EFTER_VURD_FRIST int
  ,ANTAL_INDEN_VURD_FRIST int
  ,ANTAL_DAGE_VURD int
  ,DIM_BRANCHE_AMR_P int
  ,DIM_BRANCHE_DB07_J int
  ,DIM_BRANCHE_DB07_P int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,DIM_BRANCHE_TG_P int
  ,DIM_ATVIRK int
  ,DIM_B_CENTER_A int
  ,DIM_B_CENTER_BS int
  ,DIM_B_CENTER_L int
  ,DIM_B_CENTER_P int
  ,DIM_ENHEDSTYPE int
  ,DIM_FRISTSTATUS int
  ,DIM_FRISTTYPE int
  ,DIM_JN_VURD_FRIST_OVERSKREDET int
  ,DIM_LOKATION int
  ,DIM_MEDARBEJDER_SVAR int
  ,DIM_MEDARBEJDER_REAK int
  ,DIM_ORG_ENHED_SVAR int
  ,DIM_ORG_ENHED_REAK int
  ,DIM_PRODUKTIONSENHED bigint
  ,DIM_REAKTION int
  ,DIM_TID_AFSENDT int
  ,DIM_TID_FRISTDATO int
  ,DIM_TID_MODTAGET int
  ,DIM_TID_VURDERING int
  ,DIM_VURDERING int
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
)
GO
CREATE TABLE DMSA.FACT_TILSYNF_PLANLAGT_GROVP(
   PRODUCERET_VTIMER float
  ,TOTAL_ANTAL_POINT int
  ,ESTIMERET_VTIMER float
  ,DIM_PLANLAEGNINGSENHED int
  ,DIM_PRODUKTIONSENHED bigint
  ,DIM_VIRKSOMHEDSGRUPPE int
  ,DIM_BESOEGDATO_FORVENTET int
  ,ANTAL_TILSYNSFORLOEB_PLANLAGT int
  ,DIM_TILSYNF_STATUS_GROVP int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_AMR_P_DIM int
  ,B_CENTER_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_TILSYNKRAV_PRODPLAN(
   ANTAL_VTIMER_KRAV int
  ,DIM_PLANLAEGNINGSENHED int
  ,DIM_VIRKSOMHEDSGRUPPE int
  ,DIM_BESOEGSMAANED int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_TILSYNSAKTIVITET(
   TID_DIM int
  ,PRODUKTIONSENHED_DIM bigint
  ,ATVIRK_DIM int
  ,BYGGEPLADS_DIM int
  ,LOKATION_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,BESOEGSSTATUS_DIM int
  ,FORSOEGT_BESOEGT_DIM int
  ,TILSYNSAKTIVITET_DIM int
  ,MEDARBEJDER_DIM int
  ,DIM_ORG_ENHED int
  ,BESOEGSNR int
  ,ENHEDSTYPE_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_B_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,GEOGRAFI_DIM int
  ,DIM_PLANLAEGNINGSENHED int
  ,ANTAL_AKTIVITETER int
  ,ANTAL_MED_AKTIVITETER int
  ,ANTAL_AKTIVITETSTIMER float
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.FACT_TILSYNSREAKTIONER(
   REAKTION_ID int
  ,AKTNUMMER bigint
  ,SAGSNUMMER bigint
  ,ARBEJDSMILJOEPROBLEM_DIM int
  ,MEDARBEJDER_DIM int
  ,AARSAGER_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,TILSYNSFORM_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,LOKATION_DIM int
  ,JURIDISK_ENHED_DIM bigint
  ,PRODUKTIONSENHED_DIM bigint
  ,ATVIRK_DIM int
  ,ENHEDSTYPE_DIM int
  ,BESOEG_PAA_ENHEDSTYPE_DIM int
  ,BYGGEPLADS_DIM int
  ,REAKTION_DIM int
  ,GEOGRAFI_DIM int
  ,ANSV_BELIGGENHEDSCENTER_DIM int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_B_DIM int
  ,B_CENTER_J_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,DIM_GEOGRAFI_BS int
  ,DIM_GEOGRAFI_A int
  ,DIM_GEOGRAFI_J int
  ,DIM_GEOGRAFI_L int
  ,DIM_GEOGRAFI_P int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_J_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,KONSTATERING_TID_DIM int
  ,AFSENDT_TID_DIM int
  ,I_RUT_PAA_KONST_TID_JN_DIM int
  ,DOKUMENTNR bigint
  ,DOKUMENT_TITEL nvarchar(1000)
  ,BESOEGSNR int
  ,TILSYNSAKTIVITET_DIM int
  ,ORG_ENHED_DIM int
  ,ANTAL_TILSYNSREAKTIONER int
  ,ANTAL_AFGOERELSER int
  ,ANTAL_VEJLEDNINGER int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_UDL_VIRK_BESOEG(
   OPRETTET_TID_DIM int
  ,RUT_OPRETTET_TID_DIM int
  ,BESOEG_TID_DIM int
  ,FRIST_START_TID_DIM int
  ,BESOEGT_FOER_RUT_OPRET_JN_DIM int
  ,AARSAGER_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,BESOEGSNR int
  ,ANTAL_UDL_VIRK_UDTAGET int
  ,ANTAL_UDL_VIRK_BESOEGT int
  ,ANTAL_UDL_VIRK_FORSOEGT_BESOEG int
  ,ANTAL_UDL_VIRK_AFLYST int
  ,ANTAL_UDL_VIRK_PLANLAGT int
  ,ANTAL_UDL_VIRK_INGEN_BESOEG int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_ULYKKE(
   LBNREASY int
  ,HOVEDULYKKEID int
  ,AFVIGELSE_FRITEKST nvarchar(50)
  ,ANTAL_ULYKKER int
  ,ANSAT_FRA date
  ,ANSAT_TIL date
  ,ANTAL_DAGE_ANSAT float
  ,FORLOEB nvarchar(4000)
  ,FORLOEB_FRITEKST nvarchar(50)
  ,SKADELIDTE_RUT_NR nvarchar(4000)
  ,ULYKKESTIDSPUNKT nvarchar(10)
  ,DIM_AFVIGELSE_E5 int
  ,DIM_ULYKKE_ALDER int
  ,DIM_ULYKKE_ANMELDERTYPE int
  ,DIM_ULYKKE_ANMELDERTYPE_E5 int
  ,DIM_ANSAETTELSESFORM int
  ,DIM_ANSAETTELSESFORM_E5 int
  ,DIM_B_CENTER_J int
  ,DIM_B_CENTER_P int
  ,DIM_BRANCHE_AMR_P int
  ,DIM_BRANCHE_DB07_J int
  ,DIM_BRANCHE_DB07_P int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,DIM_BRANCHE_TG_P int
  ,DIM_GEOGRAFI_ARBEJDSGIVER int
  ,DIM_GEOGRAFI_ULYKKESSTED int
  ,DIM_JN_ULYKKE_MSB int
  ,DIM_JN_ULYKKE_MSB_E5 int
  ,DIM_JN_NYANSAT int
  ,DIM_JN_ULYKKE_PSYK int
  ,DIM_JN_ULYKKE_PSYK_E5 int
  ,DIM_JOBTYPE int
  ,DIM_JOBTYPE_E5 int
  ,DIM_JURIDISK_ENHED bigint
  ,DIM_ULYKKE_KILDE int
  ,DIM_KOEN int
  ,DIM_PRODUKTIONSENHED bigint
  ,DIM_SKADEMAADE int
  ,DIM_SKADEMAADE_E5 int
  ,DIM_SKADENS_ART int
  ,DIM_SKADENS_ART_E5 int
  ,DIM_SKADENS_FOELGER int
  ,DIM_SKADENS_FOELGER_E5 int
  ,DIM_SKADET_LEGEMSDEL int
  ,DIM_SKADET_LEGEMSDEL_E5 int
  ,DIM_SKADETYPE int
  ,DIM_SKADETYPE_E5 int
  ,DIM_STATSBORGERSKAB int
  ,DIM_TEKNIK int
  ,DIM_TID_DATO_REGISTRERING int
  ,DIM_TID_DATO_ULYKKE int
  ,DIM_ULYKKESSTED int
  ,DIM_ULYKKESSTED_E5 int
  ,DIM_VOLD int
  ,DIM_JN_VOLD int
  ,DIM_JN_ANMELDEPLIGTIG int
  ,DIM_JN_UNDERSOEGELSE_UDFOERT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ float
)
GO
CREATE TABLE DMSA.FACT_ULYKKER_AKTUELLE_TAL(
   REGISTRERINGSAAR date
  ,ANTAL_ULYKKER int
  ,ANTAL_ULYKKER_MED_DOEDSFALD int
  ,ANTAL_ULYKKER_MED_KNOGLEBRUD int
  ,ANTAL_ULYKKER_MED_AMPUTATION int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_ULYKKE_KVOTERING(
   HOVEDULYKKEID int
  ,LBNREASY int
  ,FORLOEB_FRITEKST nvarchar(50)
  ,AFVIGELSE_FRITEKST nvarchar(50)
  ,SKADELIDTE_RUT_NR nvarchar(4000)
  ,ULYKKESTIDSPUNKT nvarchar(10)
  ,FORLOEB nvarchar(4000)
  ,ANTAL_ULYKKER int
  ,ANSAT_TIL date
  ,ANSAT_FRA date
  ,ANTAL_DAGE_ANSAT float
  ,DIM_AFVIGELSE_E5 int
  ,DIM_ULYKKE_ALDER int
  ,DIM_ULYKKE_ANMELDERTYPE int
  ,DIM_ULYKKE_ANMELDERTYPE_E5 int
  ,DIM_ANSAETTELSESFORM int
  ,DIM_ANSAETTELSESFORM_E5 int
  ,DIM_B_CENTER_J int
  ,DIM_B_CENTER_P int
  ,DIM_BRANCHE_AMR_P int
  ,DIM_BRANCHE_DB07_J int
  ,DIM_BRANCHE_DB07_P int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,DIM_BRANCHE_TG_P int
  ,DIM_GEOGRAFI_ARBEJDSGIVER int
  ,DIM_GEOGRAFI_ULYKKESSTED int
  ,DIM_JN_112 int
  ,DIM_JN_ULYKKE_MSB int
  ,DIM_JN_ULYKKE_MSB_E5 int
  ,DIM_JN_NYANSAT int
  ,DIM_JN_ULYKKE_PSYK int
  ,DIM_JN_ULYKKE_PSYK_E5 int
  ,DIM_JN_UNS_OPRETTET int
  ,DIM_JOBTYPE int
  ,DIM_JOBTYPE_E5 int
  ,DIM_JURIDISK_ENHED bigint
  ,DIM_ULYKKE_KILDE int
  ,DIM_KOEN int
  ,DIM_PRODUKTIONSENHED bigint
  ,DIM_SKADEMAADE int
  ,DIM_SKADEMAADE_E5 int
  ,DIM_SKADENS_ART int
  ,DIM_SKADENS_ART_E5 int
  ,DIM_SKADENS_FOELGER int
  ,DIM_SKADENS_FOELGER_E5 int
  ,DIM_SKADET_LEGEMSDEL int
  ,DIM_SKADET_LEGEMSDEL_E5 int
  ,DIM_SKADETYPE int
  ,DIM_SKADETYPE_E5 int
  ,DIM_STATSBORGERSKAB int
  ,DIM_TEKNIK int
  ,DIM_TID_DATO_REGISTRERING int
  ,DIM_TID_DATO_ULYKKE int
  ,DIM_ULYKKESSTED int
  ,DIM_ULYKKESSTED_E5 int
  ,DIM_VOLD int
  ,DIM_JN_VOLD int
  ,DIM_AFVISNINGSGRUND int
  ,DIM_JN_KVOTERET int
  ,DIM_KVOTERINGSPULJE int
  ,DIM_KVOTERINGSSTATUS int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ float
)
GO
CREATE TABLE DMSA.FACT_VIRKSTATISTIK(
   DIM_BRANCHE_AMR_P int
  ,DIM_BRANCHE_DB07_P int
  ,DIM_B_CENTER_P int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,DIM_BRANCHE_TG_P int
  ,DIM_JURIDISK_ENHED bigint
  ,DIM_B_CENTER_J int
  ,DIM_BRANCHE_DB07_J int
  ,DIM_GEOGRAFI_J int
  ,DIM_JN_CERTIFICERET int
  ,DIM_JN_LANDSDAEKKENDE int
  ,PNR bigint
  ,DIM_GEOGRAFI_P int
  ,PRODUKTIONSENHED_NAVN nvarchar(250)
  ,DIM_UDKOERSELSSTED int
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,ADRESSE nvarchar(50)
  ,ANTAL_PRODUKTIONSENHEDER int
  ,ANTAL_AARSVAERK float
  ,ANTAL_AARSVAERK_DIM int
  ,ANTAL_ANSATTE int
  ,ANTAL_ANSATTE_DIM int
  ,ANTAL_ANSATTE_2_DIM int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FACT_VIRK_TILSYN(
   TILSYNSFORLOEB_ID int
  ,TILSYNSFORLOEB_ID_UDFOERT int
  ,BESOEG_VIRK_ID int
  ,BESOEGSNR int NOT NULL
  ,BESOEGSNR_UDFOERT int
  ,BESOEGSNR_FORSOEGT_BESOEGT int
  ,ENHEDSNR bigint NOT NULL
  ,ENHEDSNR_UDFOERT bigint
  ,ENH_ID int
  ,ENHEDSNR_BSSTED bigint
  ,ENH_ID_BSSTED int
  ,SAGSNUMMER bigint
  ,DIM_ATVIRK int
  ,DIM_ATVIRK_BSSTED int
  ,DIM_B_CENTER_A int
  ,DIM_B_CENTER_A_BSSTED int
  ,DIM_B_CENTER_B_BSSTED int
  ,DIM_B_CENTER_BSSTED int
  ,DIM_B_CENTER_J int
  ,DIM_B_CENTER_L int
  ,DIM_B_CENTER_L_BSSTED int
  ,DIM_B_CENTER_P int
  ,DIM_B_CENTER_P_BSSTED int
  ,DIM_BESOEG_VIRK_FAMILIE int
  ,DIM_BESOEGSSTATUS int
  ,DIM_BRANCHE_DB07_P int
  ,DIM_BRANCHE_DB07_P_BSSTED int
  ,DIM_BRANCHE_FAELLESKAB_P int
  ,DIM_BRANCHE_FAELLESK_P_BSSTED int
  ,DIM_BRANCHE_TG_P int
  ,DIM_BRANCHE_TG_P_BSSTED int
  ,DIM_BYGGEPLADS_BSSTED int
  ,DIM_ENHEDSTYPE int
  ,DIM_ENHEDSTYPE_BSSTED int
  ,DIM_FORSOEGT_BESOEGT int
  ,DIM_GEOGRAFI_A int
  ,DIM_GEOGRAFI_A_BSSTED int
  ,DIM_GEOGRAFI_B_BSSTED int
  ,DIM_GEOGRAFI_BS int
  ,DIM_GEOGRAFI_J int
  ,DIM_GEOGRAFI_L int
  ,DIM_GEOGRAFI_L_BSSTED int
  ,DIM_GEOGRAFI_P int
  ,DIM_GEOGRAFI_P_BSSTED int
  ,DIM_JN_BSSTED int
  ,DIM_JURIDISK_ENHED bigint
  ,DIM_LOKATION int
  ,DIM_LOKATION_BSSTED int
  ,DIM_PLANLAEGNINGSENHED int
  ,DIM_PRODUKTIONSENHED bigint
  ,DIM_PRODUKTIONSENHED_BSSTED bigint
  ,DIM_TID_BESOEG int
  ,DIM_UDENLANDSK_VIRKSOMHED int
  ,DIM_UDKOERSELSSTED int
  ,DIM_VIRKSOMHEDSGRUPPE int
  ,DIM_AARSAGER int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.FORSOEGT_BESOEGT_DIM(
   FORSOEGT_BESOEGT_DIM int NOT NULL PRIMARY KEY
  ,FORSOEGTBESOEGT_KODENR nvarchar(10)
  ,FORSOEGTBESOEGT_KODEVAERDI nvarchar(50)
  ,FORSOEGTBESOEGT_TEKST nvarchar(50)
  ,FORSOEGTBESOEGT_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.FRISTTYPE_DIM(
   FRISTTYPE_DIM int NOT NULL PRIMARY KEY
  ,FRISTTYPE_KODENR nvarchar(10)
  ,FRISTTYPE_KODEVAERDI nvarchar(50)
  ,FRISTTYPE_TEKST nvarchar(100)
  ,FRISTTYPE_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.GEOGRAFI_DIM(
   GEOGRAFI_DIM int NOT NULL PRIMARY KEY
  ,REGION_NR int
  ,REGION_NAVN nvarchar(50)
  ,UDKOERSELSSTED_KODE nvarchar(10)
  ,UDKOERSELSSTED_NAVN nvarchar(20)
  ,KOMMUNE_NR int
  ,KOMMUNE_NAVN nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.JN_DIM(
   JN_DIM int NOT NULL PRIMARY KEY
  ,JN_KODE char(1)
  ,JN_TEKST nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.JURIDISK_ENHED_DIM(
   JURIDISK_ENHED_DIM bigint NOT NULL PRIMARY KEY
  ,CVRNR int
  ,JURIDISK_ENHED_NAVN nvarchar(500)
  ,ADRESSE nvarchar(50)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,BRANCHEGRUPPE_KODE nvarchar(10)
  ,BRANCHEGRUPPE_NAVN nvarchar(100)
  ,BRANCHEGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_KODE nvarchar(10)
  ,BRANCHE_NAVN nvarchar(100)
  ,BRANCHE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_DB07_DIM int
  ,BRANCHE_ARBEJDSMILJOERAAD_DIM int
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,VIRKSOMHEDSFORM nvarchar(100)
  ,LANDSDAEKKENDE_J_N nvarchar(10)
  ,CERTIFICERET nvarchar(50)
  ,STATUS int
  ,ANTAL_PROD_I_JUR int
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.JURIDISK_ENHED_DIM_VIRKSTAT(
   JURIDISK_ENHED_DIM bigint NOT NULL PRIMARY KEY
  ,CVRNR int
  ,JURIDISK_ENHED_NAVN nvarchar(250)
  ,ADRESSE nvarchar(50)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,BRANCHEGRUPPE_KODE nvarchar(10)
  ,BRANCHEGRUPPE_NAVN nvarchar(100)
  ,BRANCHEGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_KODE nvarchar(10)
  ,BRANCHE_NAVN nvarchar(100)
  ,BRANCHE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_DB07_DIM int
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,VIRKSOMHEDSFORM nvarchar(100)
  ,LANDSDAEKKENDE_J_N nvarchar(10)
  ,CERTIFICERET nvarchar(50)
  ,STATUS int
  ,ANTAL_PROD_I_JUR int
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO date
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.KAU_BESOEG_UDFOERT(
   BESOEG_UDFOERT_JN nvarchar(4000)
  ,ULYKHAEN_SA_SAGSNUMMER float
)
GO
CREATE TABLE DMSA.KEMISKE_SYGDOMME_DIM(
   KEMISKE_SYGDOMME_DIM int NOT NULL PRIMARY KEY
  ,KEMISKE_SYGDOMME_KODE_1 nvarchar(10)
  ,KEMISKE_SYGDOMME_NAVN_1 nvarchar(10)
  ,KEMISKE_SYGDOMME_SORT_1 nvarchar(10)
  ,KEMISKE_SYGDOMME_CONCAT_1 nvarchar(20)
  ,KEMISKE_SYGDOMME_KODE nvarchar(100)
  ,KEMISKE_SYGDOMME_NAVN nvarchar(100)
  ,KEMISKE_SYGDOMME_SORT nvarchar(100)
  ,KEMISKE_SYGDOMME_CONCAT nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.KONTOPLAN_DIM(
   KONTOPLAN_DIM int NOT NULL PRIMARY KEY
  ,NIVEAU1_NR nvarchar(10)
  ,NIVEAU1_NAVN nvarchar(100)
  ,NIVEAU1_NR_OG_NAVN nvarchar(100)
  ,NIVEAU2_NR nvarchar(20)
  ,NIVEAU2_NAVN nvarchar(100)
  ,NIVEAU2_NR_OG_NAVN nvarchar(100)
  ,AKTIV_JN_DIM int
  ,FRAVAER_JN_DIM int
  ,VIRK_TIME_KONTO_JN_DIM int
  ,TILSYNSAKTIVITET_JN_DIM int
  ,DWH_IS_ACTIVE nvarchar(10)
  ,DWH_LOAD_BATCH int
  ,DWH_LOAD_DATE date
  ,DWH_FROM_DATE date
  ,DWH_TO_DATE datetime
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.LAND_DIM(
   LAND_DIM int NOT NULL PRIMARY KEY
  ,LAND_KODE_1 nvarchar(10)
  ,LAND_NAVN_1 nvarchar(10)
  ,LAND_SORT_1 nvarchar(10)
  ,LAND_KODE nvarchar(10)
  ,LAND_NAVN nvarchar(50)
  ,LAND_CONCAT nvarchar(100)
  ,LAND_SORT nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.LEGEMSDEL_DIM(
   LEGEMSDEL_DIM int NOT NULL PRIMARY KEY
  ,LEGEMSDEL_KLASSIFIKATION_ID_1 nvarchar(10)
  ,LEGEMSDEL_KODE_1 nvarchar(10)
  ,LEGEMSDEL_NAVN_1 nvarchar(50)
  ,LEGEMSDEL_CONCAT_1 nvarchar(50)
  ,LEGEMSDEL_KLASSIFIKATION_ID_2 nvarchar(10)
  ,LEGEMSDEL_KODE_2 nvarchar(10)
  ,LEGEMSDEL_NAVN_2 nvarchar(50)
  ,LEGEMSDEL_CONCAT_2 nvarchar(50)
  ,LEGEMSDEL_KLASSIFIKATION_ID nvarchar(10)
  ,LEGEMSDEL_KODE nvarchar(10)
  ,LEGEMSDEL_NAVN nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.LEGEMSDEL_GRP_DIM(
   LEGEMSDEL_GRP_DIM int NOT NULL PRIMARY KEY
  ,LEGEMSDEL_GRP_KODE_1 nvarchar(10)
  ,LEGEMSDEL_GRP_NAVN_1 nvarchar(50)
  ,LEGEMSDEL_GRP_SORT_1 nvarchar(10)
  ,LEGEMSDEL_GRP_CONCAT_1 nvarchar(50)
  ,LEGEMSDEL_GRP_KODE nvarchar(10)
  ,LEGEMSDEL_GRP_NAVN nvarchar(50)
  ,LEGEMSDEL_GRP_SORT nvarchar(10)
  ,LEGEMSDEL_GRP_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.LOKATION_DIM(
   LOKATION_DIM int NOT NULL PRIMARY KEY
  ,ATIS_NR int
  ,NAVN nvarchar(250)
  ,RUT_REGISTRERINGSDATO datetime
  ,REGISTRERINGSDATO datetime
  ,GYLDIG_FRA datetime
  ,GYLDIG_TIL datetime
  ,STATUS int
  ,STATUS_TEKST nvarchar(20)
  ,ANTAL_ANSATTE int
  ,BELIGGENHEDSCENTER_DIM int
  ,BRANCHEHOVEDGRUPPE_KODE nvarchar(50)
  ,BRANCHEHOVEDGRUPPE_NAVN nvarchar(100)
  ,BRANCHOVEDGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHEG10_DB07_KODE nvarchar(10)
  ,BRANCHEG10_DB07_NAVN nvarchar(50)
  ,BRANCHEG10_DB07_KODE_OG_NAVN nvarchar(50)
  ,BRANCHEGRUPPE_KODE nvarchar(10)
  ,BRANCHEGRUPPE_NAVN nvarchar(100)
  ,BRANCHEGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,NACE_KODE nvarchar(10)
  ,NACE_NAVN nvarchar(100)
  ,NACE_KODE_OG_NAVN nvarchar(100)
  ,NACE_LANGTEKST nvarchar(250)
  ,NACE_KODEVAERDI_OG_LANGTEKST nvarchar(250)
  ,ADRESSE nvarchar(100)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,UDENLANDSK_VIRKSOMHED_ATIS_NR int
  ,UDENLANDSK_VIRKSOMHED_NAVN nvarchar(250)
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.MEDARBEJDER_DIM(
   MEDARBEJDER_DIM int
  ,MA_NR nvarchar(10)
  ,MEDARBNR int
  ,NAVN nvarchar(100)
  ,FORNAVN nvarchar(50)
  ,EFTERNAVN nvarchar(50)
  ,INITIALER nvarchar(10)
  ,DATO_ANSAET date
  ,DATO_FRATRAED date
  ,STILLING nvarchar(50)
  ,STILLINGSTYPE nvarchar(50)
  ,TILSYNSGRUPPE_DIM int
  ,TILSYNSGRUPPE int
  ,TILSYNSGRUPPE_NAVN nvarchar(50)
  ,NIV_NR int
  ,NAVNEKODE nvarchar(10)
  ,NIV_NAVN nvarchar(20)
  ,NIV_NAVN2 nvarchar(50)
  ,NIV_KODE int
  ,NIVEAU1 int
  ,NIVEAU1_NAVN nvarchar(20)
  ,NIVEAU2 int
  ,NIVEAU2_NAVNEKODE nvarchar(10)
  ,NIVEAU2_NAVN nvarchar(20)
  ,NIVEAU2_NAVN2 nvarchar(50)
  ,NIVEAU3 int
  ,NIVEAU3_NAVNEKODE nvarchar(20)
  ,NIVEAU3_NAVN nvarchar(20)
  ,NIVEAU3_NAVN2 nvarchar(100)
  ,NIVEAU4 int
  ,NIVEAU4_NAVNEKODE nvarchar(10)
  ,NIVEAU4_NAVN nvarchar(20)
  ,NIVEAU4_NAVN2 nvarchar(50)
  ,UDKOERSELSSTED_KODE nvarchar(10)
  ,UDKOERSELSSTED_NAVN nvarchar(20)
  ,AD_NR nvarchar(10)
  ,EMAIL nvarchar(20)
  ,OVERENSKOMSTNAVN nvarchar(100)
  ,PERS_LEDER_AD_NR nvarchar(10)
  ,PERS_LEDER_NAVN nvarchar(50)
  ,MTIME_NIVEAU1_KODE nvarchar(10)
  ,MTIME_NIVEAU1_NAVN nvarchar(50)
  ,MTIME_NIVEAU2_KODE nvarchar(10)
  ,MTIME_NIVEAU2_NAVN nvarchar(50)
  ,MTIME_NIVEAU2_CHEF_AD_NR nvarchar(10)
  ,MTIME_NIVEAU2_CHEF_NAVN nvarchar(50)
  ,MTIME_NIVEAU3_KODE nvarchar(20)
  ,MTIME_NIVEAU3_NAVN nvarchar(100)
  ,MTIME_NIVEAU3_CHEF_AD_NR nvarchar(10)
  ,MTIME_NIVEAU3_CHEF_NAVN nvarchar(50)
  ,MEDARBEJDERTYPE nvarchar(50)
  ,MEDARBEJDERTYPE_KODE int
  ,TRANSPORTFORM nvarchar(50)
  ,TRANSPORTFORM_KODE int
  ,PLANLAEGNINGSPUNKT nvarchar(20)
  ,PLANLAEGNINGSPUNKT_KODE int
  ,PLANL_ADRESSE nvarchar(50)
  ,PLANL_POSTNUMMER int
  ,PLANL_KOMMUNE nvarchar(50)
  ,PLANL_KOM_KODE int
  ,BOPAEL_ADRESSE nvarchar(50)
  ,BOPAEL_POSTNUMMER int
  ,BOPAEL_KOM_NAVN nvarchar(50)
  ,BOPAEL_KOM_KODE int
  ,UDK_ADRESSE nvarchar(50)
  ,UDK_POSTNUMMER int
  ,UDK_KOMMUNE nvarchar(20)
  ,UDK_KOM_KODE int
  ,PLANL_PUNKT nvarchar(20)
  ,BOPAEL_ETRS89_N float
  ,BOPAEL_ETRS89_E float
  ,BOPAEL_WGS84_N float
  ,BOPAEL_WGS84_E float
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.MGMT$REORG_CHECKPOINT(
   SCRIPT_ID float
  ,LAST_STEP float
)
GO
CREATE TABLE DMSA.MYNDIGHED_DIM(
   MYNDIGHED_DIM int NOT NULL PRIMARY KEY
  ,MYNDIGHED_KLASSIFIKATION_ID nvarchar(10)
  ,MYNDIGHED_KODE nvarchar(10)
  ,MYNDIGHED_NAVN nvarchar(50)
  ,MYNDIGHED_CONCAT nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.NACE_38_DIM(
   NACE_38_DIM int NOT NULL PRIMARY KEY
  ,NACE_38_KODE_1 nvarchar(10)
  ,NACE_38_NAVN_1 nvarchar(100)
  ,NACE_38_SORT_1 nvarchar(10)
  ,NACE_38_CONCAT_1 nvarchar(100)
  ,NACE_38_KODE nvarchar(10)
  ,NACE_38_NAVN nvarchar(100)
  ,NACE_38_SORT nvarchar(10)
  ,NACE_38_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.NEW_TABLE(
   REAKTION_ID int
  ,AKTNUMMER bigint
  ,SAGSNUMMER bigint
  ,ARBEJDSMILJOEPROBLEM_DIM int
  ,MEDARBEJDER_DIM int
  ,AARSAGER_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,TILSYNSFORM_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,LOKATION_DIM int
  ,JURIDISK_ENHED_DIM bigint
  ,PRODUKTIONSENHED_DIM bigint
  ,ATVIRK_DIM int
  ,ENHEDSTYPE_DIM int
  ,BESOEG_PAA_ENHEDSTYPE_DIM int
  ,BYGGEPLADS_DIM int
  ,REAKTION_DIM int
  ,GEOGRAFI_DIM int
  ,ANSV_BELIGGENHEDSCENTER_DIM int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_B_DIM int
  ,B_CENTER_J_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,DIM_GEOGRAFI_BS int
  ,DIM_GEOGRAFI_A int
  ,DIM_GEOGRAFI_J int
  ,DIM_GEOGRAFI_L int
  ,DIM_GEOGRAFI_P int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_J_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,KONSTATERING_TID_DIM int
  ,AFSENDT_TID_DIM int
  ,I_RUT_PAA_KONST_TID_JN_DIM int
  ,DOKUMENTNR bigint
  ,DOKUMENT_TITEL nvarchar(1000)
  ,BESOEGSNR int
  ,TILSYNSAKTIVITET_DIM int
  ,ORG_ENHED_DIM int
  ,ANTAL_TILSYNSREAKTIONER int
  ,ANTAL_AFGOERELSER int
  ,ANTAL_VEJLEDNINGER int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.OPGIVELSE_AF_RT_DIM(
   OPGIVELSE_AF_RT_DIM int
  ,OPGIVELSE_RT_KODENR nvarchar(10)
  ,OPGIVELSE_RT_KODEVAERDI nvarchar(50)
  ,OPGIVELSE_RT_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.ORG_ENHED_DIM(
   ORG_ENHED_DIM int NOT NULL PRIMARY KEY
  ,NIVEAU1_KODE nvarchar(10)
  ,NIVEAU1_NAVN nvarchar(50)
  ,NIVEAU2_KODE nvarchar(10)
  ,NIVEAU2_NAVN nvarchar(50)
  ,NIVEAU2_CHEF_AD_NR nvarchar(10)
  ,NIVEAU2_CHEF_NAVN nvarchar(50)
  ,NIVEAU3_KODE nvarchar(20)
  ,NIVEAU3_NAVN nvarchar(100)
  ,NIVEAU3_CHEF_AD_NR nvarchar(10)
  ,NIVEAU3_CHEF_NAVN nvarchar(50)
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_TIL_DATO date
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.OWB$TEMP_TABLES(
   PACKAGE_NAME nvarchar(4000)
  ,TABLE_NAME nvarchar(4000)
)
GO
CREATE TABLE DMSA.PAAVIRKNING_DIM(
   PAAVIRKNING_DIM int NOT NULL PRIMARY KEY
  ,PAAVIRK_KLASSIFIKATION_ID_1 nvarchar(10)
  ,PAAVIRK_KODE_1 nvarchar(20)
  ,PAAVIRK_NAVN_1 nvarchar(100)
  ,PAAVIRK_CONCAT_1 nvarchar(100)
  ,PAAVIRK_KLASSIFIKATION_ID_2 nvarchar(10)
  ,PAAVIRK_KODE_2 nvarchar(20)
  ,PAAVIRK_NAVN_2 nvarchar(100)
  ,PAAVIRK_CONCAT_2 nvarchar(100)
  ,PAAVIRK_KLASSIFIKATION_ID_3 nvarchar(10)
  ,PAAVIRK_KODE_3 nvarchar(20)
  ,PAAVIRK_NAVN_3 nvarchar(250)
  ,PAAVIRK_CONCAT_3 nvarchar(250)
  ,PAAVIRK_KLASSIFIKATION_ID_4 nvarchar(10)
  ,PAAVIRK_KODE_4 nvarchar(20)
  ,PAAVIRK_NAVN_4 nvarchar(250)
  ,PAAVIRK_CONCAT_4 nvarchar(250)
  ,PAAVIRK_KLASSIFIKATION_ID_5 nvarchar(10)
  ,PAAVIRK_KODE_5 nvarchar(20)
  ,PAAVIRK_NAVN_5 nvarchar(250)
  ,PAAVIRK_CONCAT_5 nvarchar(250)
  ,PAAVIRK_KLASSIFIKATION_ID nvarchar(10)
  ,PAAVIRK_KODE nvarchar(20)
  ,PAAVIRK_NAVN nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.PAAVIRKNING_GRP_DIM(
   PAAVIRKNING_GRP_DIM int NOT NULL PRIMARY KEY
  ,PAAVIRKNING_GRP_KODE_1 nvarchar(10)
  ,PAAVIRKNING_GRP_NAVN_1 nvarchar(50)
  ,PAAVIRKNING_GRP_SORT_1 nvarchar(10)
  ,PAAVIRKNING_GRP_CONCAT_1 nvarchar(50)
  ,PAAVIRKNING_GRP_KODE_2 nvarchar(10)
  ,PAAVIRKNING_GRP_NAVN_2 nvarchar(50)
  ,PAAVIRKNING_GRP_SORT_2 nvarchar(10)
  ,PAAVIRKNING_GRP_CONCAT_2 nvarchar(50)
  ,PAAVIRKNING_GRP_KODE nvarchar(20)
  ,PAAVIRKNING_GRP_NAVN nvarchar(250)
  ,PAAVIRKNING_GRP_SORT nvarchar(20)
  ,PAAVIRKNING_GRP_CONCAT nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.PERSON_DIM(
   PERSON_DIM int NOT NULL PRIMARY KEY
  ,KOEN nvarchar(10)
  ,KOEN_TEKST nvarchar(10)
  ,FOEDSELSDAG date
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.POSTNR_DIM(
   POSTNR_DIM int NOT NULL PRIMARY KEY
  ,POSTNR_KODE nvarchar(10)
  ,POSTNR_NAVN nvarchar(50)
  ,POSTNR_SORT nvarchar(10)
  ,POSTNR_CONCAT nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.PRODUKTIONSENHED_DIM(
   PRODUKTIONSENHED_DIM bigint NOT NULL PRIMARY KEY
  ,PNR bigint
  ,PRODUKTIONSENHED_NAVN nvarchar(250)
  ,ADRESSE nvarchar(50)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,CERTIFICERET_J_N nvarchar(10)
  ,BRANCHEGRUPPE_KODE nvarchar(10)
  ,BRANCHEGRUPPE_NAVN nvarchar(100)
  ,BRANCHEGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_ARBMILJOERAAD_KODE nvarchar(10)
  ,BRANCHE_ARBMILJOERAAD_NAVN nvarchar(50)
  ,BRANCHE_KODE nvarchar(10)
  ,BRANCHE_NAVN nvarchar(100)
  ,BRANCHE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_DB07_DIM int
  ,BRANCHE_ARBMILJOERAAD_DIM int
  ,ANTAL_ANSATTE int
  ,ANTAL_ANSATTE_GRUPPE nvarchar(50)
  ,ANTAL_ANSATTE_GRP_SORT int
  ,ANTAL_AARSVAERK float
  ,ANTAL_AARSVAERK_GRUPPE nvarchar(50)
  ,ANTAL_AARSVAERK_GRP_SORT float
  ,CVRNR int
  ,JURIDISK_ENHED_NAVN nvarchar(500)
  ,LANDSDAEKKENDE_J_N nvarchar(10)
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,TILSYNSGRUPPE_NR int
  ,TILSYNSGRUPPE_NAVN nvarchar(50)
  ,TILSYNSGRUPPE_DIM int
  ,STATUS int
  ,GEOGRAFI_DIM int
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.PRODUKTIONSENHED_DIM_ESS(
   PRODUKTIONSENHED_DIM bigint NOT NULL PRIMARY KEY
  ,PNR bigint
  ,PRODUKTIONSENHED_NAVN nvarchar(250)
  ,ADRESSE nvarchar(50)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,CERTIFICERET_J_N nvarchar(10)
  ,BRANCHEGRUPPE_KODE nvarchar(10)
  ,BRANCHEGRUPPE_NAVN nvarchar(100)
  ,BRANCHEGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_ARBMILJOERAAD_KODE nvarchar(10)
  ,BRANCHE_ARBMILJOERAAD_NAVN nvarchar(50)
  ,BRANCHE_KODE nvarchar(10)
  ,BRANCHE_NAVN nvarchar(100)
  ,BRANCHE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_DB07_DIM int
  ,BRANCHE_ARBMILJOERAAD_DIM int
  ,ANTAL_ANSATTE int
  ,ANTAL_ANSATTE_GRUPPE nvarchar(50)
  ,ANTAL_ANSATTE_GRP_SORT int
  ,ANTAL_AARSVAERK float
  ,ANTAL_AARSVAERK_GRUPPE nvarchar(50)
  ,ANTAL_AARSVAERK_GRP_SORT float
  ,CVRNR int
  ,JURIDISK_ENHED_NAVN nvarchar(250)
  ,LANDSDAEKKENDE_J_N nvarchar(10)
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,TILSYNSGRUPPE_NR int
  ,TILSYNSGRUPPE_NAVN nvarchar(50)
  ,TILSYNSGRUPPE_DIM int
  ,STATUS int
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.PRODUKTIONSENHED_DIM_RT(
   PRODUKTIONSENHED_DIM bigint NOT NULL PRIMARY KEY
  ,PNR bigint
  ,PRODUKTIONSENHED_NAVN nvarchar(250)
  ,ADRESSE nvarchar(50)
  ,POSTNR int
  ,POSTDISTRIKT nvarchar(50)
  ,POSTBOKS int
  ,CERTIFICERET_J_N nvarchar(10)
  ,BRANCHEGRUPPE_KODE nvarchar(10)
  ,BRANCHEGRUPPE_NAVN nvarchar(100)
  ,BRANCHEGRUPPE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_ARBMILJOERAAD_KODE nvarchar(10)
  ,BRANCHE_ARBMILJOERAAD_NAVN nvarchar(50)
  ,BRANCHE_KODE nvarchar(10)
  ,BRANCHE_NAVN nvarchar(100)
  ,BRANCHE_KODE_OG_NAVN nvarchar(100)
  ,BRANCHE_DB07_DIM int
  ,BRANCHE_ARBMILJOERAAD_DIM int
  ,ANTAL_ANSATTE int
  ,ANTAL_ANSATTE_GRUPPE nvarchar(50)
  ,ANTAL_ANSATTE_GRP_SORT int
  ,ANTAL_AARSVAERK float
  ,ANTAL_AARSVAERK_GRUPPE nvarchar(50)
  ,ANTAL_AARSVAERK_GRP_SORT float
  ,CVRNR int
  ,JURIDISK_ENHED_NAVN nvarchar(250)
  ,LANDSDAEKKENDE_J_N nvarchar(10)
  ,BELIGGENHEDSCENTER_NR int
  ,BELIGGENHEDSCENTER_NAVN nvarchar(50)
  ,BELIGGENHEDSCENTER_DIM int
  ,TILSYNSGRUPPE_NR int
  ,TILSYNSGRUPPE_NAVN nvarchar(50)
  ,TILSYNSGRUPPE_DIM int
  ,STATUS int
  ,GYLDIG_FRA_DATO date
  ,GYLDIG_FRA_DATO_ALT date
  ,GYLDIG_TIL_DATO datetime
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.REAKTION_DIM(
   REAKTION_DIM int NOT NULL PRIMARY KEY
  ,REAKTION_KODENR nvarchar(10)
  ,REAKTION_KODEVAERDI nvarchar(50)
  ,REAKTION_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.RESULTAT_AF_RT_DIM(
   RESULTAT_AF_RT_DIM int NOT NULL PRIMARY KEY
  ,RESULTAT_AF_RT_KODE nvarchar(10)
  ,RESULTAT_AF_RT_NAVN nvarchar(100)
  ,RESULTAT_AF_RT_SORT nvarchar(10)
  ,RESULTAT_AF_RT_CONCAT nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.SAGSFRISTER_DIM(
   SAGSFRISTER_DIM int NOT NULL PRIMARY KEY
  ,SAGSFRISTER_KODE_1 nvarchar(20)
  ,SAGSFRISTER_NAVN_1 nvarchar(10)
  ,SAGSFRISTER_SORT_1 nvarchar(20)
  ,SAGSFRISTER_CONCAT_1 nvarchar(50)
  ,SAGSFRISTER_KODE_2 nvarchar(20)
  ,SAGSFRISTER_NAVN_2 nvarchar(20)
  ,SAGSFRISTER_SORT_2 nvarchar(20)
  ,SAGSFRISTER_CONCAT_2 nvarchar(20)
  ,SAGSFRISTER_KODE_3 nvarchar(50)
  ,SAGSFRISTER_NAVN_3 nvarchar(10)
  ,SAGSFRISTER_SORT_3 nvarchar(50)
  ,SAGSFRISTER_CONCAT_3 nvarchar(50)
  ,SAGSFRISTER_KODE nvarchar(50)
  ,SAGSFRISTER_NAVN nvarchar(10)
  ,SAGSFRISTER_SORT nvarchar(50)
  ,SAGSFRISTER_CONCAT nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.SAGSTYPE_DIM(
   SAGSTYPE_DIM int NOT NULL PRIMARY KEY
  ,SAGSTYPE_X_KODENR_1 nvarchar(10)
  ,SAGSTYPE_X_KODEVAERDI_1 nvarchar(10)
  ,SAGSTYPE_X_TEKST_1 nvarchar(100)
  ,SAGSTYPE_X_CONCAT_1 nvarchar(100)
  ,SAGSTYPE_X_KODENR_2 nvarchar(10)
  ,SAGSTYPE_X_KODEVAERDI_2 nvarchar(20)
  ,SAGSTYPE_X_TEKST_2 nvarchar(100)
  ,SAGSTYPE_X_CONCAT_2 nvarchar(100)
  ,SAGSTYPE_KODENR_3 nvarchar(10)
  ,SAGSTYPE_KODEVAERDI_3 nvarchar(50)
  ,SAGSTYPE_TEKST_3 nvarchar(100)
  ,SAGSTYPE_CONCAT_3 nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.SOC_DUMP_ANMELDERTYPE_DIM(
   SOC_DUMP_ANMELDERTYPE_DIM int NOT NULL PRIMARY KEY
  ,ANMELDERTYPE nvarchar(50)
  ,ANMELDERROLLE nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.STILLING_DIM(
   STILLING_DIM int NOT NULL PRIMARY KEY
  ,STILLING_KLASSIFIKATION_ID_1 nvarchar(10)
  ,STILLING_KODE_1 nvarchar(10)
  ,STILLING_NAVN_1 nvarchar(100)
  ,STILLING_CONCAT_1 nvarchar(100)
  ,STILLING_KLASSIFIKATION_ID_2 nvarchar(10)
  ,STILLING_KODE_2 nvarchar(10)
  ,STILLING_NAVN_2 nvarchar(250)
  ,STILLING_CONCAT_2 nvarchar(250)
  ,STILLING_KLASSIFIKATION_ID nvarchar(10)
  ,STILLING_KODE nvarchar(10)
  ,STILLING_NAVN nvarchar(250)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.TID_AARTIER_DIM(
   TID_AARTIER_DIM int NOT NULL PRIMARY KEY
  ,AARTI int
  ,AARTI_TEKST nvarchar(10)
  ,AARSTAL int
  ,AARSTAL_TEKST nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.TID_DIM(
   TID_DIM int NOT NULL PRIMARY KEY
  ,AARSTAL int
  ,HALVAAR_NR int
  ,HALVAAR_NAVN nvarchar(20)
  ,AAR_KVARTAL int
  ,KVARTAL_NAVN nvarchar(20)
  ,AR_MAANED int
  ,MAANED_NR int
  ,MAANED_NAVN nvarchar(20)
  ,AAR_UGE int
  ,UGE_NAVN nvarchar(20)
  ,DAG_NR_I_UGE int
  ,DAG_NR_I_MAANED int
  ,DAG_NR_I_AAR int
  ,DAG_NAVN nvarchar(10)
  ,DATO date
  ,DATO_NAVN nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,ARBEJDSDAG int
  ,HELLIGDAG_NAVN nvarchar(50)
)
GO
CREATE TABLE DMSA.TILSYN2(
   REAKTION_ID int
  ,AKTNUMMER bigint
  ,SAGSNUMMER bigint
  ,ARBEJDSMILJOEPROBLEM_DIM int
  ,MEDARBEJDER_DIM int
  ,AARSAGER_DIM int
  ,VIRKSOMHEDSGRUPPE_DIM int
  ,TILSYNSFORM_DIM int
  ,UDENLANDSK_VIRKSOMHED_DIM int
  ,LOKATION_DIM int
  ,JURIDISK_ENHED_DIM bigint
  ,PRODUKTIONSENHED_DIM bigint
  ,ATVIRK_DIM int
  ,ENHEDSTYPE_DIM int
  ,BESOEG_PAA_ENHEDSTYPE_DIM int
  ,BYGGEPLADS_DIM int
  ,REAKTION_DIM int
  ,GEOGRAFI_DIM int
  ,ANSV_BELIGGENHEDSCENTER_DIM int
  ,B_CENTER_BS_DIM int
  ,B_CENTER_A_DIM int
  ,B_CENTER_B_DIM int
  ,B_CENTER_J_DIM int
  ,B_CENTER_L_DIM int
  ,B_CENTER_P_DIM int
  ,DIM_GEOGRAFI_BS int
  ,DIM_GEOGRAFI_A int
  ,DIM_GEOGRAFI_J int
  ,DIM_GEOGRAFI_L int
  ,DIM_GEOGRAFI_P int
  ,BRANCHE_AMR_P_DIM int
  ,BRANCHE_DB07_J_DIM int
  ,BRANCHE_DB07_P_DIM int
  ,BRANCHE_TG_P_DIM int
  ,DIM_BRANCHE_FAELLESSKAB_P int
  ,KONSTATERING_TID_DIM int
  ,AFSENDT_TID_DIM int
  ,I_RUT_PAA_KONST_TID_JN_DIM int
  ,DOKUMENTNR bigint
  ,DOKUMENT_TITEL nvarchar(1000)
  ,BESOEGSNR int
  ,TILSYNSAKTIVITET_DIM int
  ,ORG_ENHED_DIM int
  ,ANTAL_TILSYNSREAKTIONER int
  ,ANTAL_AFGOERELSER int
  ,ANTAL_VEJLEDNINGER int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.TILSYNSAKTIVITET_DIM(
   TILSYNSAKTIVITET_DIM int
  ,T_AKTIVITET_MTIME_KONTONR nvarchar(10)
  ,T_AKTIVITET_MTIME_NAVN nvarchar(100)
  ,T_AKTIVITET_MTIME_NR_OG_NAVN nvarchar(100)
  ,T_AKTIVITET_ATIS_KODENR int
  ,T_AKTIVITET_ATIS_KODEVAERDI nvarchar(50)
  ,T_AKTIVITET_ATIS_TEKST nvarchar(50)
  ,T_AKTIVITET_SORT int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_FROM_DATE date
  ,DWH_TO_DATE date
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.TILSYNSFORM_DIM(
   TILSYNSFORM_DIM int NOT NULL PRIMARY KEY
  ,TILSYNSFORM_KODENR nvarchar(10)
  ,TILSYNSFORM_KODEVAERDI nvarchar(50)
  ,TILSYNSFORM_TEKST nvarchar(100)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.TILSYNSGRUPPE_DIM(
   TILSYNSGRUPPE_DIM int NOT NULL PRIMARY KEY
  ,TILSYNSGRUPPE_ID int
  ,TILSYNSGRUPPE_NR int
  ,TILSYNSGRUPPE_NAVN nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.UDENLANDSK_VIRKSOMHED_DIM(
   UDENLANDSK_VIRKSOMHED_DIM int NOT NULL PRIMARY KEY
  ,ATIS_NR int
  ,NAVN nvarchar(250)
  ,RUT_NR nvarchar(10)
  ,RUT_REGISTRERINGSDATO datetime
  ,REGISTRERINGSDATO datetime
  ,FRIST_STARTDATO datetime
  ,ADRESSE nvarchar(250)
  ,POSTNR nvarchar(50)
  ,POSTDISTRIKT nvarchar(50)
  ,BYNAVN nvarchar(100)
  ,LAND_GRP_KODE nvarchar(10)
  ,LAND_GRP_TEKST nvarchar(10)
  ,LAND_KODE nvarchar(10)
  ,LAND_TEKST nvarchar(50)
  ,LAND_CONCAT nvarchar(100)
  ,FULDT_OPRETTET_JN nvarchar(10)
  ,STATUS int
  ,STATUS_TEKST nvarchar(20)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.UDKOERSELSSTED_DIM(
   UDKOERSELSSTED_DIM int NOT NULL PRIMARY KEY
  ,UDKOERSELSSTED_KODE nvarchar(10)
  ,UDKOERSELSSTED_NAVN nvarchar(10)
  ,UDKOERSELSSTED_SORT nvarchar(10)
  ,UDKOERSELSSTED_CONCAT nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.VARSLING_AFLYS_DIM(
   VARSLING_AFLYS_DIM int
  ,VARSLING_AFLYS_KODENR nvarchar(10)
  ,VARSLING_AFLYS_KODEVAERDI nvarchar(50)
  ,VARSLING_AFLYS_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.VARSLING_STATUS_DIM(
   VARSLING_STATUS_DIM int NOT NULL PRIMARY KEY
  ,VARSLING_STATUS_KODENR nvarchar(10)
  ,VARSLING_STATUS_KODEVAERDI nvarchar(50)
  ,VARSLING_STATUS_TEKST nvarchar(50)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO
CREATE TABLE DMSA.VARSL_STATUS_PRODENH_DIM(
   VARSL_STATUS_PRODENH_DIM int NOT NULL PRIMARY KEY
  ,VARSL_STATUS_PRODENH_KODE_1 nvarchar(50)
  ,VARSL_STATUS_PRODENH_NAVN_1 nvarchar(50)
  ,VARSL_STATUS_PRODENH_SORT_1 nvarchar(10)
  ,VARSL_STATUS_PRODENH_KODE nvarchar(10)
  ,VARSL_STATUS_PRODENH_NAVN nvarchar(50)
  ,VARSL_STATUS_PRODENH_SORT nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
)
GO
CREATE TABLE DMSA.VIRKSOMHEDSGRUPPE_DIM(
   VIRKSOMHEDSGRUPPE_DIM int
  ,VIRKSOMHEDSGRUPPE_NR int
  ,VIRKSOMHEDSGRUPPE_NAVN nvarchar(100)
  ,FORMAAL_NR int
  ,FORMAAL_NAVN nvarchar(100)
  ,HOVEDFORMAAL_NR int
  ,HOVEDFORMAAL_NAVN nvarchar(50)
  ,VIRKSOMHEDSPULJE_NR int
  ,VIRKSOMHEDSPULJE_NAVN nvarchar(20)
  ,DWH_HUB_SEQ int
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,VIRKSOMHEDSPULJE_NR_NAVN nvarchar(20)
  ,VIRKSOMHEDSGRUPPE_NR_NAVN nvarchar(100)
)
GO
CREATE TABLE DMSA.VURDERING_DIM(
   VURDERING_DIM int NOT NULL PRIMARY KEY
  ,EFFEKT_NIVEAU_KODENR_3 nvarchar(10)
  ,EFFEKT_NIVEAU_KODEVAERDI_3 nvarchar(10)
  ,EFFEKT_NIVEAU_TEKST_3 nvarchar(10)
  ,EFFEKT_NIVEAU_CONCAT_3 nvarchar(10)
  ,DWH_LOAD_DATE date
  ,DWH_LOAD_BATCH int
  ,DWH_HUB_SEQ int
)
GO