CREATE VIEW [DMSA].[v_Fact_Ordre_Partitioneret]
	AS 

SELECT [Bkey_Kunde]
      ,[Order_Id]
      ,[Eval_Set]
      ,[Order_Number]
      ,[Year]
      ,[Order_Dow]
      ,[Order_Hour_Of_Day]
      ,[Days_Since_Prior_Order]
      ,[Bkey_Produkt]
      ,[Add_To_Cart_Order]
      ,[Reordered]
      ,[Initial_Load_Time]
      ,[Meta_CreateTime]
      ,[Meta_CreateJob]
FROM [DMSA].[Fact_Ordre_2020]

UNION ALL

SELECT [Bkey_Kunde]
      ,[Order_Id]
      ,[Eval_Set]
      ,[Order_Number]
      ,[Year]
      ,[Order_Dow]
      ,[Order_Hour_Of_Day]
      ,[Days_Since_Prior_Order]
      ,[Bkey_Produkt]
      ,[Add_To_Cart_Order]
      ,[Reordered]
      ,[Initial_Load_Time]
      ,[Meta_CreateTime]
      ,[Meta_CreateJob]
  FROM [DMSA].[Fact_Ordre_2021]