USE DM
GO

IF HOST_NAME() LIKE 'AT-%' BEGIN
	UPDATE DMSA.FACT_ULYKKE_KVOTERING		SET DIM_PRODUKTIONSENHED = -1 WHERE DIM_PRODUKTIONSENHED % 100 > 0
	UPDATE DMSA.FACT_TILSYNF_PLANLAGT_GROVP	SET DIM_PRODUKTIONSENHED = -1 WHERE DIM_PRODUKTIONSENHED % 100 > 0
	UPDATE DMSA.FACT_TILBAGEMELDINGER		SET DIM_PRODUKTIONSENHED = -1 WHERE DIM_PRODUKTIONSENHED % 100 > 0
	UPDATE DMSA.Fact_Virksomheder_Tilsyn	SET DIM_PRODUKTIONSENHED = -1 WHERE DIM_PRODUKTIONSENHED % 100 > 0
	UPDATE DMSA.TILSYN2						SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.FACT_AFRAPPORTERING_AF_RT	SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.FACT_TILSYNSAKTIVITET		SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.FACT_RAADGIVNINGSPAABUD_AMP	SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.PRODUKTIONSENHED_DIM_RT		SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.FACT_RAADGIVNINGSPAABUD		SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.FACT_LIDELSER				SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	UPDATE DMSA.FACT_BESOEG					SET PRODUKTIONSENHED_DIM = -1 WHERE PRODUKTIONSENHED_DIM % 100 > 0
	DELETE FROM DMSA.PRODUKTIONSENHED_DIM		WHERE PRODUKTIONSENHED_DIM % 100 > 0
	DELETE FROM DMSA.PRODUKTIONSENHED_DIM_ESS	WHERE PRODUKTIONSENHED_DIM % 100 > 0
--	DELETE FROM DMSA.FACT_ERHVERVSSYGDOMME		WHERE PRODUKTIONSENHED_DIM % 100 > 0
	DELETE FROM DMSA.FACT_TILSYNSREAKTIONER		WHERE PRODUKTIONSENHED_DIM % 100 > 0
	DELETE FROM DMSA.Fact_Virksomheder_Tilsyn	WHERE DIM_PRODUKTIONSENHED % 100 > 0
	DELETE FROM DMSA.FACT_ULYKKE				WHERE DIM_PRODUKTIONSENHED % 100 > 0

	UPDATE DMSA.FACT_ULYKKE_KVOTERING		SET DIM_JURIDISK_ENHED = -1 WHERE DIM_JURIDISK_ENHED % 19 > 0
	UPDATE DMSA.Fact_Virksomhedsstatistik	SET DIM_JURIDISK_ENHED = -1 WHERE DIM_JURIDISK_ENHED % 19 > 0
	UPDATE DMSA.FACT_ULYKKE					SET DIM_JURIDISK_ENHED = -1 WHERE DIM_JURIDISK_ENHED % 19 > 0
	UPDATE DMSA.Fact_Virksomheder_Tilsyn	SET DIM_JURIDISK_ENHED = -1 WHERE DIM_JURIDISK_ENHED % 19 > 0
	UPDATE DMSA.TILSYN2						SET JURIDISK_ENHED_DIM = -1 WHERE JURIDISK_ENHED_DIM % 19 > 0
	UPDATE DMSA.FACT_RAADGIVNINGSPAABUD_AMP	SET JURIDISK_ENHED_DIM = -1 WHERE JURIDISK_ENHED_DIM % 19 > 0
	UPDATE DMSA.FACT_TILSYNSREAKTIONER		SET JURIDISK_ENHED_DIM = -1 WHERE JURIDISK_ENHED_DIM % 19 > 0
	UPDATE DMSA.FACT_RAADGIVNINGSPAABUD		SET JURIDISK_ENHED_DIM = -1 WHERE JURIDISK_ENHED_DIM % 19 > 0
	UPDATE DMSA.FACT_LIDELSER				SET JURIDISK_ENHED_DIM = -1 WHERE JURIDISK_ENHED_DIM % 19 > 0
	DELETE FROM DMSA.JURIDISK_ENHED_DIM						WHERE JURIDISK_ENHED_DIM % 19 > 0
	DELETE FROM DMSA.Dim_JuridiskEnhed_Virksomhedsstatistik	WHERE JURIDISK_ENHED_DIM % 19 > 0
	DELETE FROM DMSA.FACT_TILSYNSREAKTIONER					WHERE JURIDISK_ENHED_DIM % 19 > 0
	DELETE FROM DMSA.FACT_ULYKKE							WHERE DIM_JURIDISK_ENHED % 19 > 0
	DELETE FROM DMSA.Fact_Virksomheder_Tilsyn				WHERE DIM_JURIDISK_ENHED % 19 > 0
END
DELETE FROM DMSA.fact_tilsynsreaktioner WHERE PRODUKTIONSENHED_DIM = -1
/*
select b.name, a.name
from sys.columns a
inner join sys.tables b on a.object_id=b.object_id
where a.name in ('DIM_JURIDISK_ENHED', 'JURIDISK_ENHED_DIM')
and b.schema_id = schema_id('DMSA')
order by a.name

*/
